-- Apply to the Kollective Gateway database, not the ON CALL customer database.
-- Versioned snapshot of the verified production ON CALL catalog used for recruiting operations.

create table if not exists public.oc_live_service_catalog_snapshot (
  id text primary key,
  category_id text not null,
  name text not null,
  description text,
  base_price numeric,
  pricing_unit text,
  duration_minutes integer,
  on_demand_available boolean not null default true,
  scheduled_available boolean not null default true,
  recurring_available boolean not null default false,
  tags text[] not null default '{}',
  sort_order integer not null default 0,
  source_updated_at timestamptz,
  synced_at timestamptz not null default now(),
  is_active boolean not null default true
);

alter table public.oc_live_service_catalog_snapshot enable row level security;
revoke all on public.oc_live_service_catalog_snapshot from public,anon,authenticated;

update public.oc_live_service_catalog_snapshot set is_active=false,synced_at=now();

insert into public.oc_live_service_catalog_snapshot(id,category_id,name,sort_order,is_active,synced_at)
values
('mobile_detail','auto','Mobile Car Detail',1,true,now()),
('oil_change','auto','Mobile Oil Change',2,true,now()),
('battery_replace','auto','Battery Replacement',3,true,now()),
('tire_help','auto','Tire Help',4,true,now()),
('diagnostic','auto','Vehicle Diagnostic',5,true,now()),
('car_wash','auto','Mobile Car Wash',6,true,now()),
('admin_assistant','business','Administrative Assistant',1,true,now()),
('brand_ambassador','business','Brand Ambassador',2,true,now()),
('merchandising','business','Merchandising Support',3,true,now()),
('business_runner','business','Business Runner',4,true,now()),
('temp_staff','business','Temporary Staff',5,true,now()),
('notary','business','Mobile Notary',6,true,now()),
('bartender','events','Bartender',1,true,now()),
('server_staff','events','Event Servers',2,true,now()),
('private_chef','events','Private Chef',3,true,now()),
('event_setup','events','Event Setup & Breakdown',4,true,now()),
('event_cleanup','events','Event Cleanup Crew',5,true,now()),
('host_concierge','events','Event Host / Concierge',6,true,now()),
('babysitter','family_pet','Babysitter',1,true,now()),
('elder_companion','family_pet','Elder Companion',2,true,now()),
('dog_walk','family_pet','Dog Walking',3,true,now()),
('pet_sitting','family_pet','Pet Sitting',4,true,now()),
('house_sitting','family_pet','House Sitting',5,true,now()),
('family_runner','family_pet','Family Runner',6,true,now()),
('deep_clean','home_care','Deep Home Clean',1,true,now()),
('standard_clean','home_care','Standard Home Clean',2,true,now()),
('move_clean','home_care','Move-In / Move-Out Clean',3,true,now()),
('laundry_fold','home_care','Laundry & Fold',4,true,now()),
('home_organization','home_care','Home Organization',5,true,now()),
('trash_bin','home_care','Trash Bin Cleaning',6,true,now()),
('moving_labor','moving','Moving Labor',1,true,now()),
('pickup_delivery','moving','Pickup & Delivery',2,true,now()),
('courier','moving','Same-Day Courier',3,true,now()),
('haul_dump','moving','Haul Away',4,true,now()),
('packing','moving','Packing & Unpacking',5,true,now()),
('assembly_delivery','moving','Delivery + Assembly',6,true,now()),
('lawn_cut','outdoor','Lawn Cut & Edge',1,true,now()),
('landscaping','outdoor','Landscaping',2,true,now()),
('pressure_wash','outdoor','Pressure Washing',3,true,now()),
('gutter_clean','outdoor','Gutter Cleaning',4,true,now()),
('junk_removal','outdoor','Junk Removal',5,true,now()),
('snow_storm','outdoor','Storm & Seasonal Cleanup',6,true,now()),
('barber','personal','Mobile Barber',1,true,now()),
('makeup','personal','Makeup Artist',2,true,now()),
('hair_styling','personal','Mobile Hair Styling',3,true,now()),
('nails','personal','Mobile Nail Service',4,true,now()),
('wardrobe','personal','Wardrobe Styling',5,true,now()),
('personal_assistant','personal','Personal Assistant',6,true,now()),
('lifestyle_concierge','premium','Lifestyle Concierge',1,true,now()),
('home_manager','premium','Home Manager',2,true,now()),
('travel_assist','premium','Travel Day Assistance',3,true,now()),
('urgent_request','premium','Urgent Custom Request',4,true,now()),
('vip_event_support','premium','VIP Event Support',5,true,now()),
('estate_concierge','premium','Estate & Property Concierge',6,true,now()),
('handyman','repairs','Handyman',1,true,now()),
('plumbing','repairs','Plumbing Help',2,true,now()),
('electrician','repairs','Electrical Help',3,true,now()),
('hvac','repairs','HVAC Service',4,true,now()),
('appliance','repairs','Appliance Repair',5,true,now()),
('furniture_assembly','repairs','Furniture Assembly',6,true,now()),
('wifi_setup','tech','Wi-Fi Setup & Troubleshooting',1,true,now()),
('tv_mount','tech','TV Mounting',2,true,now()),
('smart_home','tech','Smart Home Installation',3,true,now()),
('computer_help','tech','Computer Help',4,true,now()),
('phone_setup','tech','Phone & Tablet Setup',5,true,now()),
('gaming_setup','tech','Gaming & Entertainment Setup',6,true,now()),
('massage','wellness','Mobile Massage',1,true,now()),
('personal_training','wellness','Personal Training',2,true,now()),
('yoga','wellness','Private Yoga',3,true,now()),
('stretch_recovery','wellness','Assisted Stretch & Recovery',4,true,now()),
('meal_prep','wellness','Healthy Meal Prep',5,true,now()),
('wellness_companion','wellness','Wellness Companion',6,true,now())
on conflict(id) do update set
  category_id=excluded.category_id,
  name=excluded.name,
  sort_order=excluded.sort_order,
  is_active=true,
  synced_at=now();
