import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";

const URL=Deno.env.get("SUPABASE_URL")||"",KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json","Cache-Control":"no-store"};

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 const started=Date.now(),db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}}),softwareProblems:string[]=[],activationBlockers:string[]=[];
 const count=async(table:string,build:(q:any)=>any=(q)=>q):Promise<number|null>=>{try{const{count:c,error}=await build(db.from(table).select("*",{count:"exact",head:true}));if(error)throw error;return c??0}catch{return null}};
 const secret=async(name:string):Promise<boolean>=>{if(Deno.env.get(name))return true;try{const{data,error}=await db.rpc("oc_get_runtime_secret",{secret_name:name});return !error&&Boolean(data)}catch{return false}};
 const fifteenMinAgo=new Date(Date.now()-15*60_000).toISOString();
 const[activeServices,activeCategories,activeZones,availableProviders,liveProviders,openBookings,pendingPayments,pricingRules,stripeReady,webhookReady,v2WebhookReady,vapidPublicReady,vapidPrivateReady,pushSubscriptions,pushDeliveries,openSupportCases]=await Promise.all([
  count("oc_service_catalog",q=>q.eq("is_active",true)),count("oc_service_categories",q=>q.eq("is_active",true)),count("oc_service_zones",q=>q.eq("is_active",true)),count("oc_provider_profiles",q=>q.eq("is_available",true)),count("oc_provider_locations",q=>q.eq("is_on_duty",true).gte("updated_at",fifteenMinAgo)),count("oc_bookings",q=>q.in("status",["pending","matching"])),count("oc_booking_payments",q=>q.in("status",["pending_authorization","requires_action"])),count("oc_pricing_rules",q=>q.eq("is_active",true)),secret("STRIPE_SECRET_KEY"),secret("STRIPE_WEBHOOK_SECRET"),secret("STRIPE_V2_ACCOUNT_WEBHOOK_SECRET"),secret("MARKETPLACE_VAPID_PUBLIC_KEY"),secret("MARKETPLACE_VAPID_PRIVATE_KEY"),count("marketplace_push_subscriptions"),count("marketplace_push_deliveries"),count("oc_support_tickets",q=>q.in("status",["open","reviewing","waiting_customer"]))
 ]);
 const catalogReadable=activeServices!==null&&activeCategories!==null&&activeZones!==null,catalogReady=catalogReadable&&Number(activeServices)>0&&Number(activeCategories)>0&&Number(activeZones)>0,supplyReadable=availableProviders!==null&&liveProviders!==null,paymentsReadable=pendingPayments!==null,paymentsReady=paymentsReadable&&stripeReady&&webhookReady&&v2WebhookReady&&Boolean(pricingRules),pushReady=vapidPublicReady&&vapidPrivateReady&&pushSubscriptions!==null&&pushDeliveries!==null,supportReady=openSupportCases!==null;
 if(!catalogReadable)softwareProblems.push("catalog_unreadable");else if(!catalogReady)softwareProblems.push("catalog_not_configured");if(!supplyReadable)softwareProblems.push("supply_unreadable");if(!paymentsReadable)softwareProblems.push("payments_unreadable");if(!stripeReady)softwareProblems.push("stripe_secret_missing");if(!webhookReady)softwareProblems.push("stripe_webhook_secret_missing");if(!v2WebhookReady)softwareProblems.push("stripe_v2_account_webhook_secret_missing");if(!pricingRules)softwareProblems.push("no_take_rate_configured");if(!vapidPublicReady)softwareProblems.push("push_public_key_missing");if(!vapidPrivateReady)softwareProblems.push("push_private_key_missing");if(pushSubscriptions===null||pushDeliveries===null)softwareProblems.push("push_tables_unreadable");if(!supportReady)softwareProblems.push("support_unreadable");
 if(availableProviders===0)activationBlockers.push("no_available_providers");if(liveProviders===0)activationBlockers.push("no_live_providers");
 const fatal=softwareProblems.some(p=>p.endsWith("_unreadable")),softwareStatus=fatal?"unhealthy":softwareProblems.length?"degraded":"ok",activationStatus=activationBlockers.length?"blocked":"ready";
 return new Response(JSON.stringify({app:"on_call",status:softwareStatus,software_status:softwareStatus,activation_status:activationStatus,software_ready:softwareStatus==="ok",market_activation_ready:activationStatus==="ready",software_problems:softwareProblems,activation_blockers:activationBlockers,checks:{catalog:{ready:catalogReady},supply:{readable:supplyReadable,verified_supply:Boolean(availableProviders&&availableProviders>0),live_supply:Boolean(liveProviders&&liveProviders>0)},demand:{readable:openBookings!==null},payments:{ready:paymentsReady,stripe_server_credential:stripeReady,webhook_signature_secret:webhookReady,stripe_v2_account_webhook_secret:v2WebhookReady,payments_table_reachable:paymentsReadable,take_rate_configured:Boolean(pricingRules),money_unit:"integer_cents"},push:{ready:pushReady},support:{table_reachable:supportReady}},latency_ms:Date.now()-started,checked_at:new Date().toISOString()},null,2),{status:fatal?503:200,headers:cors});
});
