import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.0";

const URL = Deno.env.get("SUPABASE_URL") || "";
const KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json","Cache-Control":"no-store"};

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 const started=Date.now();const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});const checks:Record<string,unknown>={};const softwareProblems:string[]=[];const activationBlockers:string[]=[];
 const count=async(table:string,build:(q:any)=>any=(q)=>q):Promise<number|null>=>{try{const{count:c,error}=await build(db.from(table).select("*",{count:"exact",head:true}));if(error)throw error;return c??0}catch{return null}};
 const secret=async(name:string):Promise<string>=>{if(Deno.env.get(name))return"runtime_env";try{const{data,error}=await db.rpc("oc_get_runtime_secret",{secret_name:name});if(!error&&data)return"vault"}catch{}return"missing"};
 const fifteenMinAgo=new Date(Date.now()-15*60_000).toISOString();
 const[activeServices,activeCategories,activeZones,availableProviders,liveProviders,openBookings,pendingPayments,pricingRules,stripeSource,webhookSource,v2WebhookSource,vapidPublicSource,vapidPrivateSource,pushSubscriptions,pushDeliveries,openSupportCases]=await Promise.all([
  count("oc_service_catalog",q=>q.eq("is_active",true)),count("oc_service_categories",q=>q.eq("is_active",true)),count("oc_service_zones",q=>q.eq("is_active",true)),count("oc_provider_profiles",q=>q.eq("is_available",true)),count("oc_provider_locations",q=>q.eq("is_on_duty",true).gte("updated_at",fifteenMinAgo)),count("oc_bookings",q=>q.in("status",["pending","matching"])),count("oc_booking_payments",q=>q.in("status",["pending_authorization","requires_action"])),count("oc_pricing_rules",q=>q.eq("is_active",true)),secret("STRIPE_SECRET_KEY"),secret("STRIPE_WEBHOOK_SECRET"),secret("STRIPE_V2_ACCOUNT_WEBHOOK_SECRET"),secret("MARKETPLACE_VAPID_PUBLIC_KEY"),secret("MARKETPLACE_VAPID_PRIVATE_KEY"),count("marketplace_push_subscriptions"),count("marketplace_push_deliveries"),count("oc_support_tickets",q=>q.in("status",["open","reviewing","waiting_customer"]))
 ]);
 const pushReady=vapidPublicSource!=="missing"&&vapidPrivateSource!=="missing"&&pushSubscriptions!==null&&pushDeliveries!==null;
 checks.catalog={active_services:activeServices,active_categories:activeCategories,active_zones:activeZones};checks.supply={available_providers:availableProviders,live_providers:liveProviders};checks.demand={open_bookings:openBookings};checks.payments={stripe_server_credential:stripeSource!=="missing",webhook_signature_secret:webhookSource!=="missing",stripe_v2_account_webhook_secret:v2WebhookSource!=="missing",credential_sources:{stripe:stripeSource,webhook:webhookSource,v2_account_webhook:v2WebhookSource},payments_table_reachable:pendingPayments!==null,pending_payments:pendingPayments,take_rate_rules_configured:pricingRules,money_unit:"integer_cents"};checks.push={ready:pushReady,vapid_public_key:vapidPublicSource!=="missing",vapid_private_key:vapidPrivateSource!=="missing",subscription_table_reachable:pushSubscriptions!==null,delivery_table_reachable:pushDeliveries!==null,subscriptions:pushSubscriptions,delivery_rows:pushDeliveries};checks.support={table_reachable:openSupportCases!==null,active_cases:openSupportCases};
 if(activeServices===null||activeCategories===null||activeZones===null)softwareProblems.push("catalog_unreadable");if(!activeServices)softwareProblems.push("no_active_services");if(!activeCategories)softwareProblems.push("no_active_categories");if(!activeZones)softwareProblems.push("no_active_zones");if(availableProviders===null||liveProviders===null)softwareProblems.push("supply_unreadable");if(pendingPayments===null)softwareProblems.push("payments_unreadable");if(stripeSource==="missing")softwareProblems.push("stripe_secret_missing");if(webhookSource==="missing")softwareProblems.push("stripe_webhook_secret_missing");if(v2WebhookSource==="missing")softwareProblems.push("stripe_v2_account_webhook_secret_missing");if(!pricingRules)softwareProblems.push("no_take_rate_configured");if(vapidPublicSource==="missing")softwareProblems.push("push_public_key_missing");if(vapidPrivateSource==="missing")softwareProblems.push("push_private_key_missing");if(pushSubscriptions===null||pushDeliveries===null)softwareProblems.push("push_tables_unreadable");if(openSupportCases===null)softwareProblems.push("support_unreadable");
 if(availableProviders===0)activationBlockers.push("no_available_providers");if(liveProviders===0)activationBlockers.push("no_live_providers");
 const fatal=softwareProblems.some(p=>p.endsWith("_unreadable"));const softwareStatus=fatal?"unhealthy":softwareProblems.length?"degraded":"ok";const activationStatus=activationBlockers.length?"blocked":"ready";
 return new Response(JSON.stringify({app:"on_call",status:softwareStatus,software_status:softwareStatus,activation_status:activationStatus,software_ready:softwareStatus==="ok",market_activation_ready:activationStatus==="ready",software_problems:softwareProblems,activation_blockers:activationBlockers,problems:softwareProblems,checks,latency_ms:Date.now()-started,checked_at:new Date().toISOString()},null,2),{status:fatal?503:200,headers:cors});
});
