import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import Stripe from 'npm:stripe@18.5.0';
import { createClient } from 'npm:@supabase/supabase-js@2.112.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{
  const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Authentication required');
  const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const{data:{user}}=await admin.auth.getUser(token);if(!user)throw new Error('Authentication required');
  let stripeKey=Deno.env.get('STRIPE_SECRET_KEY')||'';if(!stripeKey){const{data,error}=await admin.rpc('sos_get_runtime_secret',{secret_name:'STRIPE_SECRET_KEY'});if(!error&&data)stripeKey=String(data)}
  const{bookingId,action='quote',expectedFeeAmount}=await req.json();if(typeof bookingId!=='string')return json({error:'bookingId is required'},422);
  const{data:u}=await admin.from('oc_users').select('id,role').eq('auth_id',user.id).maybeSingle();if(!u||u.role!=='provider')throw new Error('Provider account required');
  const{data:p}=await admin.from('oc_provider_profiles').select('id').eq('user_id',u.id).maybeSingle();if(!p)throw new Error('Provider account required');
  const{data:b}=await admin.from('oc_bookings').select('*').eq('id',bookingId).eq('provider_id',p.id).maybeSingle();if(!b)throw new Error('Assigned booking not found');
  const{data:cfgRow}=await admin.from('oc_system_config').select('config_value').eq('config_key','cancellation_policy').eq('is_active',true).maybeSingle();const cfg=cfgRow?.config_value||{};const wait=Math.max(1,Math.min(120,Number(cfg.customer_no_show_wait_minutes||10)));
  const{data:policyQuote,error:quoteError}=await admin.rpc('oc_customer_cancellation_quote',{p_booking_id:bookingId});if(quoteError)throw quoteError;const q=Array.isArray(policyQuote)?policyQuote[0]:policyQuote;
  const feeCents=Math.max(0,Math.round(Number(q?.fee_cents||0))),providerCents=Math.max(0,Math.round(Number(q?.provider_compensation_cents||0))),platformCents=Math.max(0,feeCents-providerCents);
  const waitSeconds=wait*60,elapsedSeconds=b.arrived_at?Math.max(0,Math.floor((Date.now()-new Date(b.arrived_at).getTime())/1000)):0,remainingSeconds=Math.max(0,waitSeconds-elapsedSeconds);
  const{data:pay}=await admin.from('oc_booking_payments').select('*').eq('booking_id',bookingId).maybeSingle();const canSettle=b.status==='on_site'&&Boolean(b.arrived_at)&&remainingSeconds===0&&Boolean(q?.can_cancel)&&pay?.status==='authorized'&&Boolean(pay?.stripe_payment_intent_id);
  const quote={bookingId,status:b.status,canSettle,waitMinutes:wait,secondsRemaining:remainingSeconds,remainingMinutes:Math.ceil(remainingSeconds/60),feeAmount:feeCents/100,fee:feeCents/100,providerCompensation:providerCents/100,reason:b.status!=='on_site'?'No-show settlement unlocks after arrival':remainingSeconds>0?`Wait ${Math.ceil(remainingSeconds/60)} more minute${Math.ceil(remainingSeconds/60)===1?'':'s'}`:pay?.status!=='authorized'?'Customer payment authorization is required':!pay?.stripe_payment_intent_id?'Customer payment authorization is unavailable':'Eligible for customer no-show settlement'};
  if(action==='quote')return json(quote);if(action!=='settle')return json({error:'action must be quote or settle'},422);if(!canSettle)throw new Error(quote.reason);if(expectedFeeAmount!=null&&Math.round(Number(expectedFeeAmount)*100)!==feeCents)throw new Error('No-show quote changed. Review the latest amount before confirming.');if(!stripeKey)throw new Error('STRIPE_SECRET_KEY is not configured');
  const{data:canceled,error:stateError}=await admin.rpc('oc_provider_customer_no_show_v2',{p_booking_id:bookingId,p_actor_auth_id:user.id,p_fee_cents:feeCents,p_provider_compensation_cents:providerCents,p_policy_version:Number(q?.policy_version||1),p_wait_minutes:wait});if(stateError)throw stateError;
  let settlementPending=false;
  const patch:any={settlement_type:'customer_no_show',cancellation_fee_cents:feeCents,original_platform_fee:pay.original_platform_fee??pay.platform_fee,original_provider_amount:pay.original_provider_amount??pay.provider_amount,platform_fee:platformCents,provider_amount:providerCents,status:feeCents>0?'capture_pending':'authorized',updated_at:new Date().toISOString()};
  const{error:prepError}=await admin.from('oc_booking_payments').update(patch).eq('id',pay.id);if(prepError){settlementPending=true;console.error('ON CALL no-show settlement preparation queued for retry',{bookingId,paymentId:pay.id,error:prepError.message})}
  if(!prepError){try{const stripe=new Stripe(stripeKey,{httpClient:Stripe.createFetchHttpClient()});if(feeCents===0){const pi=await stripe.paymentIntents.cancel(pay.stripe_payment_intent_id,{cancellation_reason:'requested_by_customer'},{idempotencyKey:`oc-no-show-${pay.id}-free-v1`});await admin.from('oc_booking_payments').update({status:'authorization_canceled',stripe_payment_intent_id:pi.id,canceled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',pay.id)}else{const pi=await stripe.paymentIntents.capture(pay.stripe_payment_intent_id,{amount_to_capture:feeCents,final_capture:true,metadata:{settlement_type:'customer_no_show',cancellation_fee_cents:String(feeCents)}},{idempotencyKey:`oc-no-show-${pay.id}-${feeCents}-v2`});const chargeId=typeof pi.latest_charge==='string'?pi.latest_charge:pi.latest_charge?.id||pay.stripe_charge_id||null;await admin.from('oc_booking_payments').update({status:providerCents>0?'transfer_pending':'captured',amount_captured:pi.amount_received??feeCents,stripe_charge_id:chargeId,captured_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',pay.id)}}catch(error){settlementPending=true;console.error('ON CALL no-show payment queued for retry',{bookingId,paymentId:pay.id,error:String(error)})}}
  try{const number=`OC-I-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase()}`;await admin.from('oc_incident_reports').insert({incident_number:number,booking_id:bookingId,provider_id:p.id,customer_id:b.customer_id,incident_type:'customer_no_show',severity:'low',description:`Customer no-show after ${wait}-minute wait`,status:'open'})}catch(error){console.error('ON CALL no-show incident logging failed',{bookingId,error:String(error)})}
  return json({...quote,ok:true,booking:canceled,paymentSettlement:settlementPending?'pending_retry':'settled',settlementError:settlementPending?'Payment settlement will retry automatically.':undefined},settlementPending?202:200);
 }catch(e){const m=e instanceof Error?e.message:'Unexpected error';const config=m.endsWith('is not configured');return json({error:config?'Payments are not configured for this release.':m},config?503:m==='Authentication required'?401:400)}
});