import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import Stripe from 'npm:stripe@18.5.0';
import { createClient } from 'npm:@supabase/supabase-js@2.112.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{
  const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Authentication required');
  const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const{data:{user}}=await admin.auth.getUser(token);if(!user)throw new Error('Authentication required');
  let stripeKey=Deno.env.get('STRIPE_SECRET_KEY')||'';if(!stripeKey){const{data,error}=await admin.rpc('sos_get_runtime_secret',{secret_name:'STRIPE_SECRET_KEY'});if(!error&&data)stripeKey=String(data)}
  const{bookingId,reason}=await req.json();if(typeof bookingId!=='string')return json({error:'bookingId is required'},422);
  const{data:profile}=await admin.from('oc_users').select('id').eq('auth_id',user.id).maybeSingle();if(!profile)throw new Error('ON CALL account required');const{data:booking}=await admin.from('oc_bookings').select('*').eq('id',bookingId).eq('customer_id',profile.id).maybeSingle();if(!booking)throw new Error('Booking not found');
  const{data:quote,error:qerr}=await admin.rpc('oc_customer_cancellation_quote',{p_booking_id:bookingId});if(qerr)throw qerr;const q=Array.isArray(quote)?quote[0]:quote;if(!q?.can_cancel)throw new Error(q?.reason||'Booking cannot be canceled');
  const feeCents=Math.max(0,Math.round(Number(q.fee_cents||0))),providerCents=Math.max(0,Math.round(Number(q.provider_compensation_cents||0))),platformCents=Math.max(0,feeCents-providerCents);
  const{data:payment}=await admin.from('oc_booking_payments').select('*').eq('booking_id',bookingId).maybeSingle();if(feeCents>0&&(!payment?.stripe_payment_intent_id||payment.status!=='authorized'))throw new Error('Late cancellation fee requires an active payment authorization');if(payment?.stripe_payment_intent_id&&!stripeKey)throw new Error('STRIPE_SECRET_KEY is not configured');
  const{data:canceled,error:cerr}=await admin.rpc('oc_customer_cancel_v2',{p_booking_id:bookingId,p_reason:typeof reason==='string'?reason:null});if(cerr)throw cerr;
  let settlementPending=false;
  if(payment){const patch:any={settlement_type:'customer_cancellation',cancellation_fee_cents:feeCents,original_platform_fee:payment.original_platform_fee??payment.platform_fee,original_provider_amount:payment.original_provider_amount??payment.provider_amount,platform_fee:platformCents,provider_amount:providerCents,updated_at:new Date().toISOString()};if(feeCents>0)patch.status='capture_pending';const{error:prepError}=await admin.from('oc_booking_payments').update(patch).eq('id',payment.id);if(prepError){settlementPending=true;console.error('ON CALL compatibility cancellation prep queued for retry',{bookingId,paymentId:payment.id,error:prepError.message})}else if(payment.stripe_payment_intent_id){try{const stripe=new Stripe(stripeKey,{httpClient:Stripe.createFetchHttpClient()});if(feeCents===0){const pi=await stripe.paymentIntents.cancel(payment.stripe_payment_intent_id,{cancellation_reason:'requested_by_customer'},{idempotencyKey:`oc-cancel-booking-${payment.id}-free-v1`});await admin.from('oc_booking_payments').update({status:'authorization_canceled',stripe_payment_intent_id:pi.id,canceled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',payment.id)}else{const pi=await stripe.paymentIntents.capture(payment.stripe_payment_intent_id,{amount_to_capture:feeCents,final_capture:true,metadata:{settlement_type:'customer_cancellation',cancellation_fee_cents:String(feeCents)}},{idempotencyKey:`oc-cancel-booking-${payment.id}-${feeCents}-v2`});const chargeId=typeof pi.latest_charge==='string'?pi.latest_charge:pi.latest_charge?.id||payment.stripe_charge_id||null;await admin.from('oc_booking_payments').update({status:'transfer_pending',amount_captured:pi.amount_received??feeCents,stripe_charge_id:chargeId,captured_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',payment.id)}}catch(error){settlementPending=true;console.error('ON CALL compatibility cancellation settlement queued for retry',{bookingId,paymentId:payment.id,error:String(error)})}}
  }
  return json({ok:true,booking:canceled,cancellation:{fee:feeCents/100,provider_compensation:providerCents/100,policy_version:q.policy_version,reason:q.reason},paymentSettlement:settlementPending?'pending_retry':'settled'},settlementPending?202:200);
 }catch(e){const m=e instanceof Error?e.message:'Unexpected error';const config=m.endsWith('is not configured');return json({error:config?'Payments are not configured for this release.':m},config?503:m==='Authentication required'?401:400)}
});