import { useEffect,useMemo,useRef,useState } from 'react'
import { supabase } from './supabase'

type Booking={id:string;service_name:string;status:string;customer_id:string;provider_id:string|null}
type Message={id:string;booking_id:string;sender_type:'customer'|'provider'|'system';sender_id:string;content:string;is_read:boolean;read_at?:string|null;created_at:string}

export default function BookingChatHost(){
 const[booking,setBooking]=useState<Booking|null>(null),[userId,setUserId]=useState(''),[messages,setMessages]=useState<Message[]>([]),[open,setOpen]=useState(false),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const scrollRef=useRef<HTMLDivElement|null>(null)
 const loadMessages=async(id:string)=>{const{data,error}=await supabase.from('oc_chat_messages').select('id,booking_id,sender_type,sender_id,content,is_read,read_at,created_at').eq('booking_id',id).order('created_at',{ascending:true}).limit(200);if(error)throw error;setMessages((data||[]) as Message[])}
 const findBooking=async()=>{
  const{data:{session}}=await supabase.auth.getSession();if(!session?.user){setBooking(null);setUserId('');return}
  const{data:u}=await supabase.from('oc_users').select('id,role').eq('auth_id',session.user.id).maybeSingle();if(!u){setBooking(null);return}setUserId(u.id)
  let query=supabase.from('oc_bookings').select('id,service_name,status,customer_id,provider_id').in('status',['assigned','en_route','on_site','working','completed']).order('created_at',{ascending:false}).limit(10)
  if(u.role==='provider'){const{data:p}=await supabase.from('oc_provider_profiles').select('id').eq('user_id',u.id).maybeSingle();if(!p){setBooking(null);return}query=query.eq('provider_id',p.id)}else query=query.eq('customer_id',u.id)
  const{data}=await query;const now=Date.now();const current=((data||[]) as any[]).find(row=>row.status!=='completed'||now-new Date(row.completed_at||0).getTime()<=86400000)||((data||[])[0] as any)||null
  setBooking(current)
  if(current)await loadMessages(current.id);else setMessages([])
 }
 useEffect(()=>{let disposed=false;let channel:ReturnType<typeof supabase.channel>|null=null;const connect=async()=>{await findBooking();if(disposed)return};connect().catch(()=>{});const focus=()=>connect().catch(()=>{});window.addEventListener('focus',focus);const t=window.setInterval(()=>connect().catch(()=>{}),12000);return()=>{disposed=true;window.clearInterval(t);window.removeEventListener('focus',focus);if(channel)supabase.removeChannel(channel)}},[])
 useEffect(()=>{if(!booking)return;let disposed=false;const setup=async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return;supabase.realtime.setAuth(session.access_token);const channel=supabase.channel(`oc-booking-chat:${booking.id}`).on('postgres_changes',{event:'*',schema:'public',table:'oc_chat_messages',filter:`booking_id=eq.${booking.id}`},()=>{if(!disposed)loadMessages(booking.id).catch(()=>{})}).subscribe();return channel};let ch:any;setup().then(x=>ch=x);return()=>{disposed=true;if(ch)supabase.removeChannel(ch)}},[booking?.id])
 useEffect(()=>{if(open&&booking){supabase.rpc('oc_mark_booking_messages_read',{p_booking_id:booking.id}).then(()=>loadMessages(booking.id)).catch(()=>{});setTimeout(()=>scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:'smooth'}),60)}},[open,booking?.id,messages.length])
 const unread=useMemo(()=>messages.filter(m=>m.sender_id!==userId&&!m.is_read).length,[messages,userId])
 const send=async()=>{if(!booking||busy||!draft.trim())return;setBusy(true);setError('');const text=draft.trim();setDraft('');const{error}=await supabase.rpc('oc_send_booking_message',{p_booking_id:booking.id,p_content:text});if(error){setError(error.message);setDraft(text)}else await loadMessages(booking.id).catch(()=>{});setBusy(false)}
 if(!booking)return null
 return <>
  <button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',right:16,bottom:92,zIndex:1350,border:0,borderRadius:999,padding:'11px 14px',background:'#0b1727',color:'#fff',fontSize:10,fontWeight:900,letterSpacing:'.06em',boxShadow:'0 14px 40px rgba(0,0,0,.28)'}}>CHAT{unread>0?<span style={{marginLeft:7,padding:'2px 6px',borderRadius:999,background:'#1a6bff',fontSize:9}}>{unread}</span>:null}</button>
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2100,background:'rgba(3,8,15,.62)',display:'grid',placeItems:'end center',padding:12,backdropFilter:'blur(7px)'}}><section style={{width:'min(620px,100%)',height:'min(680px,82dvh)',borderRadius:24,background:'#f7f9fc',boxShadow:'0 32px 100px rgba(0,0,0,.42)',display:'grid',gridTemplateRows:'auto 1fr auto',overflow:'hidden'}}>
   <header style={{padding:'15px 17px',background:'#071426',color:'#fff',display:'flex',alignItems:'center',justifyContent:'space-between',gap:12}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',color:'#76cfff'}}>ON CALL CHAT · {booking.status.replaceAll('_',' ').toUpperCase()}</small><strong style={{display:'block',fontSize:15,marginTop:3}}>{booking.service_name}</strong></div><button type="button" onClick={()=>setOpen(false)} style={{width:34,height:34,border:0,borderRadius:12,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></header>
   <div ref={scrollRef} style={{overflowY:'auto',padding:'16px 14px',display:'flex',flexDirection:'column',gap:9}}>{messages.length===0?<div style={{margin:'auto',textAlign:'center',color:'#8490a5',fontSize:12}}><strong style={{display:'block',fontSize:16,color:'#334155'}}>Message your booking partner.</strong><span style={{display:'block',marginTop:5}}>Keep service details and arrival coordination inside ON CALL.</span></div>:messages.map(m=>{const mine=m.sender_id===userId;return <div key={m.id} style={{alignSelf:mine?'flex-end':'flex-start',maxWidth:'82%'}}><div style={{padding:'10px 12px',borderRadius:mine?'15px 15px 4px 15px':'15px 15px 15px 4px',background:mine?'#1765e8':'#fff',color:mine?'#fff':'#1f2937',fontSize:12,lineHeight:1.48,boxShadow:mine?'none':'0 6px 20px rgba(15,23,42,.08)',border:mine?'0':'1px solid #e5eaf1'}}>{m.content}</div><small style={{display:'block',marginTop:3,textAlign:mine?'right':'left',color:'#9aa4b5',fontSize:8}}>{mine?'YOU':m.sender_type.toUpperCase()} · {new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>})}</div>
   <footer style={{padding:'10px 12px',borderTop:'1px solid #e5eaf1',background:'#fff'}}>{error&&<div style={{fontSize:10,color:'#c52b2b',marginBottom:7}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><textarea value={draft} onChange={e=>setDraft(e.target.value.slice(0,2000))} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message customer/provider…" style={{resize:'none',minHeight:42,maxHeight:110,border:'1px solid #dbe2ec',borderRadius:14,padding:'11px 12px',font:'inherit',fontSize:12,outline:'none'}}/><button type="button" onClick={send} disabled={busy||!draft.trim()} style={{border:0,borderRadius:14,padding:'0 17px',background:'#1765e8',color:'#fff',fontSize:11,fontWeight:900,opacity:busy||!draft.trim()?.6:1}}>SEND</button></div><small style={{display:'block',marginTop:6,color:'#9aa4b5',fontSize:8}}>Messages are limited to participants in this booking. Access closes 24 hours after completion.</small></footer>
  </section></div>}
 </>
}
