import { useEffect,useState } from 'react'
import { Elements,PaymentElement,useElements,useStripe } from '@stripe/react-stripe-js'
import { loadStripe } from '@stripe/stripe-js'
import { getMarketplacePaymentsHealth,stripeClientPublishableKeyConfigured,supabase } from './supabase'

type Address={id:string;label:string;address:string;city?:string|null;state_code?:string|null;zip_code?:string|null;is_default:boolean}
type Recurring={id:string;service_name:string;frequency:string;status:string;next_scheduled?:string|null;service_address?:string|null;price_per_visit?:number|null}
type Method={id:string;brand?:string|null;last4?:string|null;exp_month?:number|null;exp_year?:number|null;is_default?:boolean}
const empty={id:'',label:'Home',address:'',city:'',state_code:'',zip_code:'',is_default:false}
const stripePromise=stripeClientPublishableKeyConfigured?loadStripe(import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY):null

function SetupCard({onDone}:{onDone:()=>void}){const stripe=useStripe(),elements=useElements(),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async()=>{if(!stripe||!elements||busy)return;setBusy(true);setError('');const{error}=await stripe.confirmSetup({elements,redirect:'if_required'});if(error)setError(error.message||'Card setup failed.');else onDone();setBusy(false)};return <div className="ocpt-setup"><PaymentElement/><button onClick={submit} disabled={!stripe||busy}>{busy?'Saving…':'Save payment method'}</button>{error&&<p>{error}</p>}</div>}

export default function CustomerProfileToolsHost(){
 const[tool,setTool]=useState<'addresses'|'payments'|'recurring'|null>(null),[addresses,setAddresses]=useState<Address[]>([]),[address,setAddress]=useState<any>(empty),[recurring,setRecurring]=useState<Recurring[]>([]),[methods,setMethods]=useState<Method[]>([]),[setupSecret,setSetupSecret]=useState(''),[health,setHealth]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const close=()=>{setTool(null);setAddress(empty);setSetupSecret('');setError('');setNotice('')}
 const loadAddresses=async()=>{const{data,error}=await supabase.from('oc_saved_addresses').select('id,label,address,city,state_code,zip_code,is_default').order('is_default',{ascending:false}).order('created_at');if(error)throw error;setAddresses((data||[]) as Address[])}
 const loadRecurring=async()=>{const{data,error}=await supabase.from('oc_recurring_schedules').select('id,service_name,frequency,status,next_scheduled,service_address,price_per_visit').order('created_at',{ascending:false});if(error)throw error;setRecurring((data||[]) as Recurring[])}
 const loadMethods=async()=>{const h=await getMarketplacePaymentsHealth(true).catch(()=>null);setHealth(h);if(!h?.ready||!stripeClientPublishableKeyConfigured){setMethods([]);return}const{data,error}=await supabase.functions.invoke('oc-payment-methods',{body:{action:'list'}});if(error)throw error;if(data?.error)throw new Error(data.error);setMethods(data.methods||[])}
 useEffect(()=>{const handler=(e:any)=>{const next=e?.detail?.tool;if(['addresses','payments','recurring'].includes(next)){setError('');setNotice('');setTool(next)}};window.addEventListener('oncall:open-profile-tool',handler);return()=>window.removeEventListener('oncall:open-profile-tool',handler)},[])
 useEffect(()=>{if(tool==='addresses')loadAddresses().catch(e=>setError(e.message));if(tool==='payments')loadMethods().catch(e=>setError(e.message));if(tool==='recurring')loadRecurring().catch(e=>setError(e.message))},[tool])
 const saveAddress=async()=>{if(busy)return;setBusy('address');setError('');const{error}=await supabase.rpc('oc_upsert_saved_address',{p_address_id:address.id||null,p_label:address.label,p_address:address.address,p_city:address.city||null,p_state_code:address.state_code||null,p_zip_code:address.zip_code||null,p_lat:null,p_lng:null,p_is_default:Boolean(address.is_default)});if(error)setError(error.message);else{setAddress(empty);await loadAddresses();setNotice('Address saved.')}setBusy('')}
 const removeAddress=async(id:string)=>{if(!confirm('Remove this saved address?'))return;const{error}=await supabase.rpc('oc_delete_saved_address',{p_address_id:id});if(error)setError(error.message);else await loadAddresses()}
 const makeDefault=async(id:string)=>{const{error}=await supabase.rpc('oc_set_default_address',{p_address_id:id});if(error)setError(error.message);else await loadAddresses()}
 const recurringStatus=async(id:string,status:string)=>{setBusy(id);const{error}=await supabase.rpc('oc_customer_set_recurring_status',{p_schedule_id:id,p_status:status});if(error)setError(error.message);else await loadRecurring();setBusy('')}
 const beginSetup=async()=>{if(!health?.ready||!stripeClientPublishableKeyConfigured)return;setBusy('setup');const{data,error}=await supabase.functions.invoke('oc-payment-methods',{body:{action:'setup'}});if(error||data?.error)setError(data?.error||error?.message||'Card setup unavailable.');else setSetupSecret(data.clientSecret);setBusy('')}
 const removeMethod=async(id:string)=>{if(!confirm('Remove this payment method?'))return;const{data,error}=await supabase.functions.invoke('oc-payment-methods',{body:{action:'remove',paymentMethodId:id}});if(error||data?.error)setError(data?.error||error?.message||'Payment method could not be removed.');else await loadMethods()}
 if(!tool)return null
 return <div className="ocpt-backdrop" role="dialog" aria-modal="true" onMouseDown={close}><section className="ocpt-sheet" onMouseDown={e=>e.stopPropagation()}><div className="ocpt-handle"/><header><div><small>CUSTOMER ACCOUNT</small><h2>{tool==='addresses'?'Saved addresses':tool==='payments'?'Payment methods':'Recurring services'}</h2><p>{tool==='addresses'?'Keep real service locations ready for faster booking.':tool==='payments'?'Cards are tokenized and managed through Stripe; ON CALL never displays a full card number.':'Pause, resume, or cancel recurring work from one place.'}</p></div><button onClick={close}>×</button></header>{error&&<div className="ocpt-error">{error}</div>}{notice&&<div className="ocpt-notice">{notice}</div>}
 {tool==='addresses'&&<><div className="ocpt-list">{addresses.map(a=><article key={a.id}><div><small>{a.is_default?'DEFAULT':'SAVED'}</small><strong>{a.label}</strong><span>{[a.address,a.city,a.state_code,a.zip_code].filter(Boolean).join(', ')}</span></div><div className="ocpt-actions"><button onClick={()=>setAddress({...a})}>Edit</button>{!a.is_default&&<button onClick={()=>makeDefault(a.id)}>Make default</button>}<button className="danger" onClick={()=>removeAddress(a.id)}>Remove</button></div></article>)}</div>{addresses.length===0&&<div className="ocpt-empty">No saved addresses yet.</div>}<div className="ocpt-form"><label>Label<input value={address.label} onChange={e=>setAddress({...address,label:e.target.value})}/></label><label className="wide">Full address<input value={address.address} onChange={e=>setAddress({...address,address:e.target.value})} placeholder="123 Main St"/></label><label>City<input value={address.city||''} onChange={e=>setAddress({...address,city:e.target.value})}/></label><label>State<input maxLength={2} value={address.state_code||''} onChange={e=>setAddress({...address,state_code:e.target.value.toUpperCase()})}/></label><label>ZIP<input value={address.zip_code||''} onChange={e=>setAddress({...address,zip_code:e.target.value})}/></label><label className="check"><input type="checkbox" checked={Boolean(address.is_default)} onChange={e=>setAddress({...address,is_default:e.target.checked})}/> Default address</label><button className="ocpt-primary wide" disabled={busy==='address'||!address.label.trim()||!address.address.trim()} onClick={saveAddress}>{busy==='address'?'Saving…':address.id?'Update address':'Add address'}</button></div></>}
 {tool==='payments'&&<><div className={`ocpt-health ${health?.ready&&stripeClientPublishableKeyConfigured?'ready':'offline'}`}><b>{health?.ready&&stripeClientPublishableKeyConfigured?'SECURE PAYMENTS ONLINE':'PAYMENTS OFFLINE'}</b><span>{!stripeClientPublishableKeyConfigured?'Stripe browser key is not configured.':health?.message||'Payment health unavailable.'}</span></div><div className="ocpt-list">{methods.map(m=><article key={m.id}><div><small>{m.is_default?'DEFAULT CARD':'CARD'}</small><strong>{String(m.brand||'card').toUpperCase()} •••• {m.last4}</strong><span>Expires {m.exp_month}/{m.exp_year}</span></div><button className="danger" onClick={()=>removeMethod(m.id)}>Remove</button></article>)}</div>{methods.length===0&&<div className="ocpt-empty">No saved payment methods.</div>}{setupSecret&&stripePromise?<Elements stripe={stripePromise} options={{clientSecret:setupSecret,appearance:{theme:'night'}}}><SetupCard onDone={async()=>{setSetupSecret('');setNotice('Payment method saved.');await loadMethods()}}/></Elements>:<button className="ocpt-primary" disabled={!health?.ready||!stripeClientPublishableKeyConfigured||busy==='setup'} onClick={beginSetup}>{health?.ready&&stripeClientPublishableKeyConfigured?'Add payment method':'Payments unavailable'}</button>}</>}
 {tool==='recurring'&&<><div className="ocpt-list">{recurring.map(r=><article key={r.id}><div><small>{r.frequency.toUpperCase()} · {r.status.toUpperCase()}</small><strong>{r.service_name}</strong><span>{r.service_address||'Service address'}{r.next_scheduled?` · next ${new Date(r.next_scheduled).toLocaleDateString()}`:''}</span></div><div className="ocpt-actions">{r.status==='active'?<button onClick={()=>recurringStatus(r.id,'paused')}>Pause</button>:r.status==='paused'?<button onClick={()=>recurringStatus(r.id,'active')}>Resume</button>:null}{r.status!=='canceled'&&<button className="danger" onClick={()=>recurringStatus(r.id,'canceled')}>Cancel</button>}</div></article>)}</div>{recurring.length===0&&<div className="ocpt-empty">No recurring services yet. Choose Recurring when booking an eligible service.</div>}</>}
 </section></div>
}
