import { useEffect,useState } from 'react'
import { supabase } from './supabase'

type Booking={id:string;service_name:string;status:string;completed_at?:string|null;canceled_at?:string|null;cancelled_at?:string|null;created_at:string}
type Receipt={booking:any;provider:any;payment:any;timeline:any[];generated_at:string}
const money=(v:any)=>`$${Number(v||0).toFixed(2)}`
const status=(v:string)=>String(v||'').replaceAll('_',' ').toUpperCase()

export default function CustomerReceiptHost(){
 const[bookings,setBookings]=useState<Booking[]>([]),[open,setOpen]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session?.user){setBookings([]);return}const{data:u}=await supabase.from('oc_users').select('id,role').eq('auth_id',session.user.id).maybeSingle();if(!u||u.role==='provider'){setBookings([]);return}const{data}=await supabase.from('oc_bookings').select('id,service_name,status,completed_at,canceled_at,cancelled_at,created_at').eq('customer_id',u.id).in('status',['completed','canceled']).order('created_at',{ascending:false}).limit(30);setBookings((data||[]) as Booking[])}
 useEffect(()=>{let disposed=false;const run=()=>{if(!disposed)load().catch(()=>{})};run();const t=window.setInterval(run,20000);return()=>{disposed=true;window.clearInterval(t)}},[])
 const view=async(id:string)=>{setBusy(true);setError('');const{data,error}=await supabase.rpc('oc_customer_receipt',{p_booking_id:id});if(error)setError(error.message);else setReceipt(data as Receipt);setBusy(false)}
 if(bookings.length===0&&!open)return null
 return <>
  {bookings.length>0&&<button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',left:16,top:76,zIndex:1490,border:'1px solid rgba(255,255,255,.13)',borderRadius:999,padding:'9px 12px',background:'rgba(7,20,38,.94)',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.08em',boxShadow:'0 12px 34px rgba(0,0,0,.25)',backdropFilter:'blur(12px)'}}>RECEIPTS</button>}
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2280,background:'rgba(3,8,15,.55)',display:'grid',justifyItems:'start',backdropFilter:'blur(6px)'}}><section style={{width:'min(520px,96vw)',height:'100dvh',background:'#f7f9fc',boxShadow:'24px 0 80px rgba(0,0,0,.35)',display:'grid',gridTemplateRows:'auto 1fr'}}>
   <header style={{padding:'18px 16px 14px',background:'#071426',color:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.13em',color:'#79d1ff'}}>ON CALL HISTORY</small><h2 style={{fontSize:23,margin:'4px 0 0'}}>{receipt?'Service receipt':'Receipts & timelines'}</h2></div><div style={{display:'flex',gap:7}}>{receipt&&<button type="button" onClick={()=>setReceipt(null)} style={{border:0,borderRadius:11,padding:'8px 10px',background:'rgba(255,255,255,.08)',color:'#fff',fontSize:9,fontWeight:900}}>BACK</button>}<button type="button" onClick={()=>{setOpen(false);setReceipt(null)}} style={{width:36,height:36,border:0,borderRadius:12,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></div></div></header>
   <div style={{overflowY:'auto',padding:13}}>{error&&<div style={{padding:10,borderRadius:12,background:'#fff0f0',color:'#b42318',fontSize:10,marginBottom:9}}>{error}</div>}{busy?<div style={{padding:50,textAlign:'center',color:'#7c8798',fontSize:11}}>Opening receipt…</div>:receipt?<ReceiptView receipt={receipt}/>:bookings.map(b=><button key={b.id} type="button" onClick={()=>view(b.id)} style={{width:'100%',textAlign:'left',border:'1px solid #e2e8f0',borderRadius:16,padding:'13px 14px',background:'#fff',marginBottom:8,cursor:'pointer'}}><small style={{fontSize:8,fontWeight:900,letterSpacing:'.1em',color:b.status==='completed'?'#16875b':'#b45309'}}>{status(b.status)}</small><strong style={{display:'block',fontSize:14,color:'#172033',marginTop:4}}>{b.service_name}</strong><span style={{display:'block',fontSize:9,color:'#8a95a7',marginTop:5}}>{new Date(b.completed_at||b.canceled_at||b.cancelled_at||b.created_at).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}</span></button>)}</div>
  </section></div>}
 </>
}

function ReceiptView({receipt}:{receipt:Receipt}){
 const p=receipt.payment||{},b=receipt.booking||{}
 const rows=[['Authorized',money(p.authorized)],['Captured',money(p.captured)],['Refunded',money(p.refunded)],['Cancellation / no-show fee',money(p.cancellation_fee)],['Provider amount',money(p.provider_amount)]]
 return <div><section style={{padding:16,borderRadius:18,background:'#fff',border:'1px solid #e2e8f0'}}><small style={{fontSize:8,fontWeight:900,letterSpacing:'.1em',color:'#1765e8'}}>{status(b.status)}</small><h3 style={{fontSize:20,margin:'5px 0 3px',color:'#172033'}}>{b.service_name}</h3><p style={{fontSize:10.5,color:'#718096',lineHeight:1.5,margin:0}}>{b.address||'Service location'}{receipt.provider?.name?` · ${receipt.provider.name}`:''}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:7,marginTop:14}}>{rows.map(([k,v])=><div key={k} style={{padding:10,borderRadius:12,background:'#f5f8fc'}}><small style={{fontSize:7.5,color:'#8995a7'}}>{k.toUpperCase()}</small><strong style={{display:'block',fontSize:14,color:'#243247',marginTop:2}}>{v}</strong></div>)}</div><div style={{marginTop:11,fontSize:9,color:'#8290a4'}}>Settlement: {status(p.settlement_type||'service')} · Payment: {status(p.status||'not created')}</div></section><h4 style={{fontSize:10,letterSpacing:'.11em',color:'#67758a',margin:'17px 4px 9px'}}>SERVICE TIMELINE</h4><div>{(receipt.timeline||[]).length===0?<div style={{fontSize:10,color:'#94a0b1',padding:12}}>No recorded events.</div>:(receipt.timeline||[]).map((e:any,i:number)=><div key={`${e.created_at}-${i}`} style={{display:'grid',gridTemplateColumns:'10px 1fr',gap:9,padding:'8px 4px'}}><i style={{width:8,height:8,borderRadius:'50%',background:'#1765e8',marginTop:3}}/><div><strong style={{fontSize:10,color:'#26344a'}}>{status(e.type||'update')}</strong>{e.description&&<span style={{display:'block',fontSize:9.5,color:'#758197',marginTop:2,lineHeight:1.4}}>{e.description}</span>}<small style={{fontSize:8,color:'#a0a8b6'}}>{e.created_at?new Date(e.created_at).toLocaleString():''}</small></div></div>)}</div></div>
}
