import { useEffect,useState } from 'react'
import { supabase } from './supabase'

type Booking={id:string;customer_id:string;service_name:string;status:string}
type Quote={bookingId:string;status:string;canCancel:boolean;feeAmount:number;providerCompensation:number;reason:string;policyVersion:number}

export default function CustomerCancellationHost(){
 const[booking,setBooking]=useState<Booking|null>(null),[quote,setQuote]=useState<Quote|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{
  let disposed=false;let channel:ReturnType<typeof supabase.channel>|null=null
  const connect=async()=>{
   const{data:{session}}=await supabase.auth.getSession();if(!session?.user||disposed)return
   const{data:user}=await supabase.from('oc_users').select('id,role').eq('auth_id',session.user.id).maybeSingle();if(!user||user.role==='provider'||disposed)return
   const refresh=async()=>{const{data:rows}=await supabase.from('oc_bookings').select('id,customer_id,service_name,status').eq('customer_id',user.id).in('status',['en_route','on_site']).order('created_at',{ascending:false}).limit(1);if(!disposed)setBooking((rows?.[0]||null) as Booking|null)}
   await refresh();supabase.realtime.setAuth(session.access_token)
   channel=supabase.channel(`oc-cancel-status:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'oc_bookings',filter:`customer_id=eq.${user.id}`},()=>refresh().catch(()=>{})).subscribe()
  }
  connect().catch(()=>{});return()=>{disposed=true;if(channel)supabase.removeChannel(channel)}
 },[])
 const start=async()=>{if(!booking||busy)return;setBusy(true);setError('');try{const{data,error}=await supabase.functions.invoke('oc-cancel-booking',{body:{bookingId:booking.id,action:'quote'}});if(error)throw error;if(data?.error)throw new Error(data.error);setQuote(data as Quote);setOpen(true)}catch(e){setError(e instanceof Error?e.message:'Cancellation quote unavailable')}finally{setBusy(false)}}
 const cancel=async()=>{if(!booking||!quote||busy)return;setBusy(true);setError('');try{const{data,error}=await supabase.functions.invoke('oc-cancel-booking',{body:{bookingId:booking.id,action:'cancel',expectedFeeAmount:Number(quote.feeAmount||0),reason:quote.reason}});if(error)throw error;if(data?.error)throw new Error(data.error);setOpen(false);setQuote(null);setBooking(null);setNotice(Number(data?.feeAmount||0)>0?`Service canceled. $${Number(data.feeAmount).toFixed(2)} cancellation fee applied.`:'Service canceled with no fee.');setTimeout(()=>setNotice(''),5000)}catch(e){setError(e instanceof Error?e.message:'Service could not be canceled')}finally{setBusy(false)}}
 if(!booking&&!open&&!notice&&!error)return null
 return <>
  {booking&&!open&&<button type="button" onClick={start} disabled={busy} style={{position:'fixed',right:16,bottom:142,zIndex:1210,border:'1px solid rgba(255,255,255,.14)',borderRadius:999,padding:'10px 13px',background:'#111827',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.06em',boxShadow:'0 12px 36px rgba(0,0,0,.28)'}}>{busy?'CHECKING…':booking.status==='on_site'?'CANCEL / PROVIDER ARRIVED':'CANCEL SERVICE'}</button>}
  {open&&quote&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:1700,display:'grid',placeItems:'end center',background:'rgba(3,8,15,.68)',backdropFilter:'blur(8px)',padding:16}}><section style={{width:'min(520px,100%)',borderRadius:24,padding:20,background:'#0b1727',color:'#fff',boxShadow:'0 30px 90px rgba(0,0,0,.5)',border:'1px solid rgba(255,255,255,.10)'}}><div style={{display:'flex',justifyContent:'space-between',gap:16}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.13em',color:'#73d9ff'}}>CANCELLATION QUOTE</small><h2 style={{fontSize:24,margin:'7px 0 5px'}}>Cancel {booking?.service_name}?</h2><p style={{margin:0,color:'rgba(255,255,255,.65)',fontSize:12,lineHeight:1.5}}>{quote.reason}</p></div><button type="button" onClick={()=>{setOpen(false);setQuote(null);setError('')}} style={{width:34,height:34,borderRadius:12,border:0,background:'rgba(255,255,255,.08)',color:'#fff',fontSize:20}}>×</button></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:18}}><div style={{padding:14,borderRadius:16,background:'rgba(255,255,255,.06)'}}><small style={{fontSize:8,color:'rgba(255,255,255,.5)',letterSpacing:'.08em'}}>CANCELLATION FEE</small><strong style={{display:'block',fontSize:26,marginTop:3}}>${Number(quote.feeAmount||0).toFixed(2)}</strong></div><div style={{padding:14,borderRadius:16,background:'rgba(255,255,255,.06)'}}><small style={{fontSize:8,color:'rgba(255,255,255,.5)',letterSpacing:'.08em'}}>PROVIDER COMPENSATION</small><strong style={{display:'block',fontSize:26,marginTop:3}}>${Number(quote.providerCompensation||0).toFixed(2)}</strong></div></div><p style={{fontSize:10,lineHeight:1.55,color:'rgba(255,255,255,.52)',margin:'14px 0'}}>The fee shown is the current policy quote for this booking state. ON CALL rechecks the fee when you confirm so it cannot silently change.</p>{error&&<div style={{padding:10,borderRadius:12,background:'rgba(255,92,104,.12)',color:'#ff9aa2',fontSize:11,marginBottom:10}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 1.5fr',gap:9}}><button type="button" onClick={()=>{setOpen(false);setQuote(null)}} disabled={busy} style={{padding:13,borderRadius:13,border:'1px solid rgba(255,255,255,.14)',background:'transparent',color:'#fff',fontWeight:800}}>Keep service</button><button type="button" onClick={cancel} disabled={busy||!quote.canCancel} style={{padding:13,borderRadius:13,border:0,background:'#e5484d',color:'#fff',fontWeight:900}}>{busy?'Canceling…':Number(quote.feeAmount||0)>0?`Cancel · $${Number(quote.feeAmount).toFixed(2)} fee`:'Cancel with no fee'}</button></div></section></div>}
  {notice&&<div role="status" style={{position:'fixed',right:16,top:78,zIndex:1600,width:'min(380px,calc(100vw - 32px))',padding:'12px 14px',borderRadius:14,background:'#0b1727',color:'#fff',fontSize:11,boxShadow:'0 18px 50px rgba(0,0,0,.3)'}}>{notice}</div>}
  {error&&!open&&<div role="alert" style={{position:'fixed',right:16,top:78,zIndex:1600,width:'min(380px,calc(100vw - 32px))',padding:'12px 14px',borderRadius:14,background:'#3b1216',color:'#ffd8dc',fontSize:11}}>{error}</div>}
 </>
}
