type LegalKind='privacy'|'terms'

const sectionStyle={margin:'24px 0'} as const
const h2Style={fontSize:18,margin:'0 0 8px',letterSpacing:'-.02em'} as const
const pStyle={margin:'7px 0',color:'#b9c6d8',fontSize:13,lineHeight:1.7} as const
const listStyle={margin:'8px 0 0',paddingLeft:20,color:'#b9c6d8',fontSize:13,lineHeight:1.7} as const

function Privacy(){return <>
  <p style={pStyle}>This Privacy Policy explains how ON CALL handles information when you create an account, request or provide services, use location features, communicate through the marketplace, make payments, or contact support.</p>
  <section style={sectionStyle}><h2 style={h2Style}>Information we handle</h2><ul style={listStyle}><li>Account and contact information such as name, email, phone number and profile details.</li><li>Service addresses and location data you choose to provide for booking, matching, routing and safety.</li><li>Booking details, messages, ratings, support requests, incident records and service history.</li><li>Provider application, identity, licensing, insurance and verification information when you apply to provide services.</li><li>Payment identifiers and transaction status. Payment-card entry is handled by Stripe; ON CALL does not need to store your full card number.</li><li>Device and push-notification information needed to deliver booking and account alerts.</li></ul></section>
  <section style={sectionStyle}><h2 style={h2Style}>How we use information</h2><p style={pStyle}>We use information to authenticate accounts, operate the marketplace, match requests, coordinate services, process and reconcile payments, communicate booking status, provide support, prevent abuse, investigate safety issues, comply with law and improve reliability.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>When information is shared</h2><p style={pStyle}>Information may be shared with the customer or provider assigned to a booking when needed to perform the service; with infrastructure, payment, messaging and security vendors that help operate ON CALL; and when required by law, safety obligations or valid legal process. Access should be limited to what is necessary for the specific purpose.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Location</h2><p style={pStyle}>Precise location is used only when you permit it or enter a service location. Location supports matching, routing, active-service status and safety. You can decline device location and enter an address manually where the service flow allows it.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Account deletion and retention</h2><p style={pStyle}>Signed-in users can delete their ON CALL account from Account &amp; Privacy. The sign-in identity and active personal profile data are removed or anonymized. Certain transaction, fraud-prevention, dispute, tax, accounting or safety records may be retained where reasonably necessary or legally required, with personal fields removed where the system can safely do so.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Security and choices</h2><p style={pStyle}>ON CALL uses access controls, restricted server credentials and verification gates designed to protect marketplace data. You can manage notification preferences, saved addresses and payment methods from your account tools. No internet system can guarantee absolute security.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Children</h2><p style={pStyle}>ON CALL accounts are intended for people who are legally able to enter service transactions. The marketplace is not directed to children under 13.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Contact</h2><p style={pStyle}>Questions about privacy or an account request can be sent to <a href="mailto:thedoctordorsey@gmail.com" style={{color:'#75b8ff'}}>thedoctordorsey@gmail.com</a>.</p></section>
</>}

function Terms(){return <>
  <p style={pStyle}>These Terms govern your use of ON CALL. By creating an account or requesting or accepting a service, you agree to these terms and to the pricing, cancellation and service details shown for that transaction.</p>
  <section style={sectionStyle}><h2 style={h2Style}>Marketplace role</h2><p style={pStyle}>ON CALL coordinates service requests with eligible providers. Services may be fulfilled by independent providers or ON CALL-affiliated operators depending on the service. Provider identity and assignment are shown only after a real provider is connected to the booking.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Eligibility and accounts</h2><p style={pStyle}>You must provide accurate information, protect your sign-in credentials and use the account only for lawful purposes. Provider access may require identity, background, licensing, insurance, service-area and payout verification before work can be accepted.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Requests and availability</h2><p style={pStyle}>Catalog listings describe services the platform supports; they do not guarantee that a provider is currently available in every market. A request is not assigned until an eligible provider accepts or is otherwise confirmed through the marketplace.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Pricing and payments</h2><p style={pStyle}>Prices, estimates, minimums and applicable fees are shown in the booking flow. ON CALL may authorize a payment method before service and capture the appropriate amount after completion or according to the cancellation/no-show terms presented for that booking. Payment processing is provided through Stripe.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Cancellations, disputes and refunds</h2><p style={pStyle}>Cancellation or no-show charges may apply when disclosed by the booking flow. If work, pricing or service quality is disputed, use the in-app support and dispute tools so the transaction can be reviewed against booking records and evidence.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Safety</h2><p style={pStyle}>ON CALL is not an emergency-response service. Do not use the marketplace in place of 911 or another emergency authority when there is immediate danger, a medical emergency, fire or crime in progress.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Prohibited use</h2><p style={pStyle}>Do not use ON CALL for fraud, unlawful activity, harassment, unsafe work, unauthorized access, payment abuse, impersonation, interference with the platform or requests that a provider cannot lawfully perform.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Suspension and termination</h2><p style={pStyle}>Accounts or marketplace access may be restricted for safety, fraud, nonpayment, verification failure, repeated policy violations or unlawful activity. You may delete your account through Account &amp; Privacy.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Service limitations</h2><p style={pStyle}>Service timing, provider availability and outcomes can vary. To the extent permitted by applicable law, ON CALL is not responsible for delays or failures caused by circumstances outside its reasonable control. Nothing in these terms removes rights that cannot legally be waived.</p></section>
  <section style={sectionStyle}><h2 style={h2Style}>Contact</h2><p style={pStyle}>Questions about these terms or a booking can be sent to <a href="mailto:thedoctordorsey@gmail.com" style={{color:'#75b8ff'}}>thedoctordorsey@gmail.com</a>.</p></section>
</>}

export default function LegalPage({kind}:{kind:LegalKind}){
  const privacy=kind==='privacy'
  return <div style={{minHeight:'100dvh',background:'linear-gradient(155deg,#06101d,#0a1c32 48%,#050b14)',color:'#fff',fontFamily:'DM Sans,system-ui,sans-serif',padding:'28px 18px 70px'}}><main style={{width:'min(820px,100%)',margin:'0 auto'}}><a href="/" style={{display:'inline-flex',alignItems:'center',gap:8,color:'#fff',textDecoration:'none',fontWeight:900,fontSize:12}}><span style={{width:34,height:34,borderRadius:11,display:'grid',placeItems:'center',background:'#fff',color:'#07101d'}}>OC</span>ON CALL</a><div style={{margin:'54px 0 28px'}}><div style={{fontSize:10,fontWeight:950,letterSpacing:'.18em',color:'#75b8ff'}}>LEGAL · EFFECTIVE AUGUST 9, 2026</div><h1 style={{fontSize:'clamp(38px,7vw,64px)',lineHeight:1,letterSpacing:'-.06em',margin:'10px 0 14px'}}>{privacy?'Privacy Policy':'Terms of Service'}</h1><p style={{...pStyle,fontSize:14,maxWidth:700}}>{privacy?'How ON CALL handles account, booking, location, provider and payment information.':'The operating rules for customers, providers, bookings and payments on ON CALL.'}</p></div><article style={{background:'rgba(10,25,43,.78)',border:'1px solid rgba(255,255,255,.1)',borderRadius:24,padding:'clamp(20px,4vw,34px)',boxShadow:'0 30px 90px rgba(0,0,0,.24)'}}>{privacy?<Privacy/>:<Terms/>}</article><nav style={{display:'flex',gap:16,flexWrap:'wrap',marginTop:22,fontSize:12}}><a href="/privacy" style={{color:'#9cc9ff'}}>Privacy</a><a href="/terms" style={{color:'#9cc9ff'}}>Terms</a><a href="mailto:thedoctordorsey@gmail.com" style={{color:'#9cc9ff'}}>Support</a><a href="/" style={{color:'#9cc9ff'}}>Back to ON CALL</a></nav></main></div>
}
