import { useEffect,useMemo,useState } from 'react'
import { supabase } from './supabase'

type Notice={id:number;user_id:string;booking_id?:string|null;type:string;title:string;body:string;is_read:boolean;read_at?:string|null;action_url?:string|null;created_at:string}

const label=(type:string)=>({message:'MESSAGE',booking_status:'BOOKING',provider_timeout:'RELIABILITY',provider_reassigned:'REASSIGNMENT',customer_no_show:'NO-SHOW'}[type]||type.replaceAll('_',' ').toUpperCase())

export default function NotificationInboxHost(){
 const[userId,setUserId]=useState(''),[items,setItems]=useState<Notice[]>([]),[open,setOpen]=useState(false),[error,setError]=useState('')
 const load=async(id?:string)=>{const uid=id||userId;if(!uid)return;const{data,error}=await supabase.from('oc_notifications').select('id,user_id,booking_id,type,title,body,is_read,read_at,action_url,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(100);if(error)throw error;setItems((data||[]) as Notice[])}
 useEffect(()=>{let channel:ReturnType<typeof supabase.channel>|null=null;let disposed=false;const connect=async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session?.user)return;const{data:u}=await supabase.from('oc_users').select('id').eq('auth_id',session.user.id).maybeSingle();if(!u||disposed)return;setUserId(u.id);await load(u.id);supabase.realtime.setAuth(session.access_token);channel=supabase.channel(`oc-notification-inbox:${u.id}`).on('postgres_changes',{event:'*',schema:'public',table:'oc_notifications',filter:`user_id=eq.${u.id}`},()=>load(u.id).catch(()=>{})).subscribe()};connect().catch(()=>{});return()=>{disposed=true;if(channel)supabase.removeChannel(channel)}},[])
 const unread=useMemo(()=>items.filter(x=>!x.is_read).length,[items])
 const mark=async(ids?:number[])=>{setError('');const{error}=await supabase.rpc('oc_mark_notifications_read',{p_notification_ids:ids?.length?ids:null});if(error){setError(error.message);return}await load()}
 const openNotice=async(item:Notice)=>{if(!item.is_read)await mark([item.id]);if(item.action_url){if(item.action_url==='/provider'&&window.location.pathname==='/provider'){setOpen(false);return}window.location.assign(item.action_url)}else setOpen(false)}
 if(!userId)return null
 return <>
  <button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',right:16,top:76,zIndex:1500,border:'1px solid rgba(255,255,255,.13)',borderRadius:999,padding:'9px 12px',background:'rgba(7,20,38,.94)',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.08em',boxShadow:'0 12px 34px rgba(0,0,0,.25)',backdropFilter:'blur(12px)'}}>INBOX{unread>0?<span style={{marginLeft:7,padding:'2px 6px',borderRadius:999,background:'#1765e8'}}>{unread>99?'99+':unread}</span>:null}</button>
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2250,background:'rgba(3,8,15,.52)',display:'grid',justifyItems:'end',backdropFilter:'blur(6px)'}}><section style={{width:'min(430px,94vw)',height:'100dvh',background:'#f7f9fc',boxShadow:'-24px 0 80px rgba(0,0,0,.35)',display:'grid',gridTemplateRows:'auto 1fr'}}>
   <header style={{padding:'18px 16px 14px',background:'#071426',color:'#fff'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.13em',color:'#79d1ff'}}>ON CALL INBOX</small><h2 style={{fontSize:23,margin:'4px 0 0'}}>Updates that matter.</h2></div><button type="button" onClick={()=>setOpen(false)} style={{width:36,height:36,border:0,borderRadius:12,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:13}}><span style={{fontSize:10,color:'rgba(255,255,255,.62)'}}>{unread} unread · {items.length} recent</span>{unread>0&&<button type="button" onClick={()=>mark()} style={{border:0,background:'transparent',color:'#8ed7ff',fontSize:9,fontWeight:900}}>MARK ALL READ</button>}</div></header>
   <div style={{overflowY:'auto',padding:12}}>{error&&<div style={{padding:10,borderRadius:12,background:'#fff0f0',color:'#b42318',fontSize:10,marginBottom:9}}>{error}</div>}{items.length===0?<div style={{padding:'60px 18px',textAlign:'center',color:'#7c8798'}}><strong style={{display:'block',fontSize:17,color:'#334155'}}>No updates yet.</strong><span style={{fontSize:11,display:'block',marginTop:5}}>Booking, message, reassignment and payment updates will stay here.</span></div>:items.map(item=><button type="button" key={item.id} onClick={()=>openNotice(item)} style={{width:'100%',textAlign:'left',border:'1px solid #e4e9f0',borderRadius:16,padding:'12px 13px',background:item.is_read?'#fff':'#edf5ff',marginBottom:8,cursor:'pointer',boxShadow:item.is_read?'none':'0 8px 24px rgba(23,101,232,.08)'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'flex-start'}}><div><small style={{fontSize:8,fontWeight:900,letterSpacing:'.1em',color:item.is_read?'#8b96a8':'#1765e8'}}>{label(item.type)}</small><strong style={{display:'block',fontSize:13,color:'#172033',marginTop:3}}>{item.title}</strong></div>{!item.is_read&&<i style={{width:8,height:8,borderRadius:'50%',background:'#1765e8',flex:'0 0 auto',marginTop:4}}/>}</div><span style={{display:'block',fontSize:10.5,lineHeight:1.48,color:'#67758a',marginTop:5}}>{item.body}</span><small style={{display:'block',fontSize:8,color:'#9aa4b5',marginTop:7}}>{new Date(item.created_at).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></button>)}</div>
  </section></div>}
 </>
}
