import React,{useEffect,useState}from'react'
import{Elements,PaymentElement,useElements,useStripe}from'@stripe/react-stripe-js'
import{loadStripe}from'@stripe/stripe-js'
import{supabase}from'./supabase'

const stripeKey=import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY as string|undefined
const stripePromise=stripeKey?loadStripe(stripeKey):null

type Panel='addresses'|'payments'|'recurring'|null

type SavedAddress={id:string;label:string;address:string;city:string|null;state_code:string|null;zip_code:string|null;is_default:boolean}
type PaymentMethod={id:string;brand:string|null;last4:string|null;exp_month:number|null;exp_year:number|null;is_default:boolean}
type Recurring={id:string;service_name:string;frequency:string;service_address:string|null;service_city:string|null;status:string;next_scheduled:string|null;price_per_visit:number|null}

function SetupCard({clientSecret,onDone}:{clientSecret:string;onDone:()=>void}){
  const stripe=useStripe();const elements=useElements();const[busy,setBusy]=useState(false);const[error,setError]=useState('')
  const submit=async()=>{if(!stripe||!elements||busy)return;setBusy(true);setError('');const result=await stripe.confirmSetup({elements,redirect:'if_required'});if(result.error)setError(result.error.message||'Card setup failed');else onDone();setBusy(false)}
  return <div className="ocx-card-setup"><PaymentElement options={{layout:'tabs'}}/><button disabled={!stripe||busy} onClick={submit}>{busy?'Saving card…':'Save payment method'}</button>{error&&<p>{error}</p>}<small>Card details are secured by Stripe. ON CALL stores only non-sensitive card metadata.</small></div>
}

export default function OnCallEnhancementHost(){
  const[panel,setPanel]=useState<Panel>(null);const[profile,setProfile]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('')
  const[addresses,setAddresses]=useState<SavedAddress[]>([]);const[methods,setMethods]=useState<PaymentMethod[]>([]);const[recurring,setRecurring]=useState<Recurring[]>([])
  const[setupSecret,setSetupSecret]=useState<string|null>(null)
  const[form,setForm]=useState({label:'Home',address:'',city:'Atlanta',state_code:'GA',zip_code:''})

  useEffect(()=>{const handler=(event:MouseEvent)=>{const button=(event.target as HTMLElement)?.closest('.oc2-menu button') as HTMLButtonElement|null;if(!button)return;const label=button.querySelector('strong')?.textContent?.trim();if(label==='Saved addresses'){event.preventDefault();setPanel('addresses')}if(label==='Payment methods'){event.preventDefault();setPanel('payments')}if(label==='Recurring services'){event.preventDefault();setPanel('recurring')}};document.addEventListener('click',handler);return()=>document.removeEventListener('click',handler)},[])

  useEffect(()=>{if(!panel)return;let active=true;(async()=>{setLoading(true);setError('');setNotice('');try{const{data:{session}}=await supabase.auth.getSession();if(!session?.user)throw new Error('Sign in to manage your account.');const{data:user,error:userError}=await supabase.from('oc_users').select('id,full_name,email').eq('auth_id',session.user.id).single();if(userError||!user)throw new Error('ON CALL profile unavailable.');if(!active)return;setProfile(user);if(panel==='addresses'){const{data,error}=await supabase.from('oc_saved_addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false}).order('created_at');if(error)throw error;setAddresses((data||[])as SavedAddress[])}if(panel==='payments'){const{data,error}=await supabase.functions.invoke('oc-payment-methods',{body:{action:'list'}});if(error)throw error;setMethods((data?.methods||[])as PaymentMethod[])}if(panel==='recurring'){const{data,error}=await supabase.from('oc_recurring_schedules').select('id,service_name,frequency,service_address,service_city,status,next_scheduled,price_per_visit').eq('customer_id',user.id).order('created_at',{ascending:false});if(error)throw error;setRecurring((data||[])as Recurring[])}}catch(e){if(active)setError(e instanceof Error?e.message:'Account data unavailable')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[panel])

  const addAddress=async()=>{if(!profile||!form.address.trim())return;setLoading(true);setError('');try{const{data,error}=await supabase.from('oc_saved_addresses').insert({user_id:profile.id,label:form.label.trim()||'Saved',address:form.address.trim(),city:form.city.trim()||null,state_code:form.state_code.trim().toUpperCase()||null,zip_code:form.zip_code.trim()||null,is_default:addresses.length===0}).select('*').single();if(error)throw error;setAddresses(v=>[data as SavedAddress,...v]);setForm(v=>({...v,address:'',zip_code:''}));setNotice('Address saved.')}catch(e){setError(e instanceof Error?e.message:'Address could not be saved')}finally{setLoading(false)}}
  const removeAddress=async(id:string)=>{setLoading(true);try{const{error}=await supabase.from('oc_saved_addresses').delete().eq('id',id);if(error)throw error;setAddresses(v=>v.filter(a=>a.id!==id));setNotice('Address removed.')}catch(e){setError(e instanceof Error?e.message:'Unable to remove address')}finally{setLoading(false)}}
  const beginCardSetup=async()=>{setLoading(true);setError('');try{const{data,error}=await supabase.functions.invoke('oc-payment-methods',{body:{action:'setup'}});if(error)throw error;if(!data?.clientSecret)throw new Error('Secure card setup is unavailable.');setSetupSecret(data.clientSecret)}catch(e){setError(e instanceof Error?e.message:'Card setup unavailable')}finally{setLoading(false)}}
  const syncCards=async()=>{setSetupSecret(null);setLoading(true);try{const{data,error}=await supabase.functions.invoke('oc-payment-methods',{body:{action:'sync'}});if(error)throw error;setMethods((data?.methods||[])as PaymentMethod[]);setNotice('Payment method saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to refresh payment methods')}finally{setLoading(false)}}
  const removeCard=async(id:string)=>{setLoading(true);try{const{error}=await supabase.functions.invoke('oc-payment-methods',{body:{action:'remove',paymentMethodId:id}});if(error)throw error;setMethods(v=>v.filter(m=>m.id!==id));setNotice('Payment method removed.')}catch(e){setError(e instanceof Error?e.message:'Unable to remove payment method')}finally{setLoading(false)}}
  const setRecurringStatus=async(id:string,status:string)=>{setLoading(true);try{const{data,error}=await supabase.rpc('oc_customer_set_recurring_status',{p_schedule_id:id,p_status:status});if(error)throw error;setRecurring(v=>v.map(item=>item.id===id?{...item,status:data.status}:item));setNotice(`Recurring service ${status}.`)}catch(e){setError(e instanceof Error?e.message:'Recurring service could not be updated')}finally{setLoading(false)}}

  if(!panel)return null
  const title=panel==='addresses'?'Saved addresses':panel==='payments'?'Payment methods':'Recurring services'
  const subtitle=panel==='addresses'?'Keep home, work, and frequent service locations ready.':panel==='payments'?'Secure cards for faster service authorization.':'Pause, resume, or cancel repeating ON CALL services.'
  return <div className="ocx-backdrop" onMouseDown={()=>setPanel(null)}><section className="ocx-sheet" onMouseDown={e=>e.stopPropagation()}><div className="ocx-handle"/><header><div><span>MY ON CALL</span><h2>{title}</h2><p>{subtitle}</p></div><button onClick={()=>setPanel(null)}>×</button></header>{loading&&<div className="ocx-progress">Updating securely…</div>}{error&&<div className="ocx-error">{error}</div>}{notice&&<div className="ocx-notice">{notice}</div>}
  {panel==='addresses'&&<><div className="ocx-list">{addresses.length===0?<div className="ocx-empty"><b>⌂</b><strong>No saved locations yet.</strong><span>Add one below and reuse it during booking.</span></div>:addresses.map(a=><article key={a.id}><div className="ocx-icon">⌂</div><div><small>{a.label}{a.is_default?' · DEFAULT':''}</small><strong>{a.address}</strong><span>{[a.city,a.state_code,a.zip_code].filter(Boolean).join(', ')}</span></div><button onClick={()=>removeAddress(a.id)}>Remove</button></article>)}</div><div className="ocx-form"><label>Label<input value={form.label} onChange={e=>setForm(v=>({...v,label:e.target.value}))}/></label><label className="wide">Street address<input value={form.address} onChange={e=>setForm(v=>({...v,address:e.target.value}))} placeholder="123 Main St"/></label><label>City<input value={form.city} onChange={e=>setForm(v=>({...v,city:e.target.value}))}/></label><label>State<input maxLength={2} value={form.state_code} onChange={e=>setForm(v=>({...v,state_code:e.target.value}))}/></label><label>ZIP<input value={form.zip_code} onChange={e=>setForm(v=>({...v,zip_code:e.target.value}))}/></label><button className="ocx-primary wide" disabled={loading||!form.address.trim()} onClick={addAddress}>Save address</button></div></>}
  {panel==='payments'&&<>{setupSecret&&stripePromise?<Elements stripe={stripePromise} options={{clientSecret:setupSecret,appearance:{theme:'night'}}}><SetupCard clientSecret={setupSecret} onDone={syncCards}/></Elements>:<><div className="ocx-list">{methods.length===0?<div className="ocx-empty"><b>▣</b><strong>No payment methods yet.</strong><span>Add a secure card to authorize matched services faster.</span></div>:methods.map(m=><article key={m.id}><div className="ocx-icon">▣</div><div><small>{m.brand?.toUpperCase()||'CARD'}{m.is_default?' · DEFAULT':''}</small><strong>•••• {m.last4||'—'}</strong><span>{m.exp_month&&m.exp_year?`Expires ${String(m.exp_month).padStart(2,'0')}/${String(m.exp_year).slice(-2)}`:'Secure payment method'}</span></div><button onClick={()=>removeCard(m.id)}>Remove</button></article>)}</div><button className="ocx-primary" onClick={beginCardSetup} disabled={loading}>+ Add payment method</button></>}</>}
  {panel==='recurring'&&<div className="ocx-list">{recurring.length===0?<div className="ocx-empty"><b>↻</b><strong>No recurring services yet.</strong><span>Choose “Recurring” when booking an eligible service.</span></div>:recurring.map(r=><article key={r.id}><div className="ocx-icon">↻</div><div><small>{r.frequency.toUpperCase()} · {r.status.toUpperCase()}</small><strong>{r.service_name}</strong><span>{r.next_scheduled?`Next ${new Date(`${r.next_scheduled}T12:00:00`).toLocaleDateString()}`:'Schedule active'}{r.service_city?` · ${r.service_city}`:''}{r.price_per_visit!=null?` · $${Number(r.price_per_visit).toFixed(0)}/visit`:''}</span></div><div className="ocx-actions">{r.status==='active'?<button onClick={()=>setRecurringStatus(r.id,'paused')}>Pause</button>:r.status==='paused'?<button onClick={()=>setRecurringStatus(r.id,'active')}>Resume</button>:null}{r.status!=='canceled'&&<button className="danger" onClick={()=>setRecurringStatus(r.id,'canceled')}>Cancel</button>}</div></article>)}</div>}
  </section></div>
}
