import { useEffect,useMemo,useState } from 'react'
import { supabase,startProviderOnboarding } from './supabase'

type Check={check_type:string;required:boolean;status:string;notes?:string|null;evidence_urls?:string[]}
type Status={state:string;application_id?:string;application_number?:string;application_status?:string;core_dispatch_ready?:boolean;services?:number;dispatch_ready_services?:number;license_required?:boolean;insurance_required?:boolean;stripe_onboarding_complete?:boolean;stripe_payouts_enabled?:boolean;checks?:Check[]}
const pretty=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const allowedTypes=new Set(['application/pdf','image/jpeg','image/png','image/webp','image/heic','image/heif'])
const extension=(file:File)=>{const fromName=file.name.split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,'');if(fromName)return fromName;return file.type==='application/pdf'?'pdf':file.type.includes('png')?'png':file.type.includes('webp')?'webp':'jpg'}

export default function ProviderVerificationReadinessHost(){
 const[status,setStatus]=useState<Status|null>(null),[open,setOpen]=useState(false),[error,setError]=useState(''),[uploading,setUploading]=useState('')
 const load=async()=>{const{data,error}=await supabase.rpc('oc_provider_verification_status');if(error)throw error;setStatus(data as Status)}
 useEffect(()=>{let alive=true;const refresh=()=>load().catch(()=>{});supabase.auth.getSession().then(({data})=>{if(alive&&data.session)refresh()});const timer=window.setInterval(refresh,12000);const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive&&s)refresh()});return()=>{alive=false;clearInterval(timer);data.subscription.unsubscribe()}},[])
 const ready=Boolean(status?.core_dispatch_ready)&&Number(status?.dispatch_ready_services||0)>0
 useEffect(()=>{if(status?.state!=='provider')return;document.documentElement.dataset.ocVerificationUi='1';document.documentElement.dataset.ocDispatchReady=ready?'true':'false';const block=(event:Event)=>{const target=event.target as HTMLElement|null;const button=target?.closest?.('.ocp-online');if(!ready&&button&&!button.classList.contains('active')){event.preventDefault();event.stopImmediatePropagation();setOpen(true)}};document.addEventListener('click',block,true);return()=>{document.removeEventListener('click',block,true);delete document.documentElement.dataset.ocVerificationUi;delete document.documentElement.dataset.ocDispatchReady}},[ready,status?.state])
 const checks=useMemo(()=>status?.checks||[],[status]);
 const visible=checks.filter(c=>c.required||['license','insurance'].includes(c.check_type));
 const done=visible.filter(c=>c.status==='passed'||(['license','insurance','vehicle'].includes(c.check_type)&&c.status==='waived')).length
 const upload=async(check:Check,file?:File)=>{if(!file||!status?.application_id)return;setError('');if(file.size>10*1024*1024){setError('Verification files must be 10 MB or smaller.');return}if(!allowedTypes.has(file.type)){setError('Use PDF, JPEG, PNG, WebP, HEIC, or HEIF files.');return}setUploading(check.check_type);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sign in again before uploading verification files.');const path=`on_call/${user.id}/${status.application_id}/${check.check_type}/${crypto.randomUUID()}.${extension(file)}`;const{error:uploadError}=await supabase.storage.from('marketplace-verification').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const{error:rpcError}=await supabase.rpc('oc_provider_submit_verification_evidence',{p_check_type:check.check_type,p_path:path});if(rpcError)throw rpcError;await load()}catch(e){setError(e instanceof Error?e.message:'Verification evidence could not be uploaded.')}finally{setUploading('')}}
 if(status?.state!=='provider'||ready)return null
 const payoutReady=Boolean(status.stripe_onboarding_complete&&status.stripe_payouts_enabled)
 return <><button className="ocvr-launch" onClick={()=>setOpen(true)}><span>SETUP REQUIRED</span><b>{done + (payoutReady?1:0)}/{visible.length+1}</b><small>{status.dispatch_ready_services||0} services ready</small></button>{open&&<div className="ocvr-backdrop" onMouseDown={()=>setOpen(false)}><section className="ocvr-sheet" onMouseDown={e=>e.stopPropagation()}><header><div><span>PROVIDER LAUNCH READINESS</span><h2>Finish verification before dispatch.</h2><p>Application approval opens Provider Command. ON CALL does not send customer work until the required checks and payout setup are complete.</p></div><button onClick={()=>setOpen(false)}>×</button></header>{error&&<div className="ocvr-error">{error}</div>}<div className="ocvr-summary"><div><small>APPLICATION</small><strong>{status.application_number||'Approved provider'}</strong><span>{pretty(status.application_status||'approved')}</span></div><div><small>APPROVED SERVICES</small><strong>{status.services||0}</strong><span>{status.dispatch_ready_services||0} dispatch-ready</span></div></div><div className="ocvr-checks">{visible.map(check=>{const ok=check.status==='passed'||(['license','insurance','vehicle'].includes(check.check_type)&&check.status==='waived');const submitted=(check.evidence_urls||[]).length;return <div key={check.check_type} className={ok?'done':''}><i>{ok?'✓':submitted?'↑':'!'}</i><span><strong>{pretty(check.check_type)}</strong><small>{check.required?'Required':'Conditional'} · {pretty(check.status)}</small>{submitted>0&&<em>{submitted} private file{submitted===1?'':'s'} submitted</em>}</span>{!ok&&<label className="ocvr-upload"><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp,image/heic,image/heif" disabled={uploading===check.check_type} onChange={e=>{const file=e.target.files?.[0];void upload(check,file);e.currentTarget.value=''}}/><b>{uploading===check.check_type?'Uploading…':submitted?'Add evidence':'Upload evidence'}</b></label>}</div>})}<div className={payoutReady?'done':''}><i>{payoutReady?'✓':'$'}</i><span><strong>Payout account</strong><small>{payoutReady?'Stripe payouts ready':'Stripe onboarding required'}</small></span></div></div>{!payoutReady&&<button className="ocvr-primary" onClick={async()=>{setError('');try{await startProviderOnboarding()}catch(e){setError(e instanceof Error?e.message:'Payout setup could not start.')}}}>Finish payout setup →</button>}<p className="ocvr-truth">Verification files are private. Identity, background, skills, and service-area checks must pass. License and insurance are enforced only for services that require them.</p></section></div>}</>
}
