import { useEffect,useState } from 'react'
import { supabase } from './supabase'

type Offer={booking_id:string;service_name?:string}
type Trust={trust_score:number;rating_count:number}
type Pending={booking_id:string;service_name:string;completed_at:string;customer_first_name?:string|null;customer_trust_score:number;customer_rating_count:number}
const TAGS=['ready_on_time','clear_instructions','respectful','safe_access','unresponsive','access_issue']
const label=(tag:string)=>({ready_on_time:'Ready on time',clear_instructions:'Clear instructions',respectful:'Respectful',safe_access:'Safe access',unresponsive:'Unresponsive',access_issue:'Access issue'}[tag]||tag)

export default function ProviderCustomerTrustHost(){
 const[offer,setOffer]=useState<Offer|null>(null),[trust,setTrust]=useState<Trust|null>(null),[pending,setPending]=useState<Pending|null>(null),[rating,setRating]=useState(5),[tags,setTags]=useState<string[]>([]),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[dismissed,setDismissed]=useState(false),[notice,setNotice]=useState('')
 const load=async()=>{
  const{data:{session}}=await supabase.auth.getSession();if(!session?.user){setOffer(null);setTrust(null);setPending(null);return}
  const{data:u}=await supabase.from('oc_users').select('id,role').eq('auth_id',session.user.id).maybeSingle();if(!u||u.role!=='provider'){setOffer(null);setTrust(null);setPending(null);return}
  const{data:offers}=await supabase.rpc('oc_provider_active_offers');const next=(offers?.[0]||null) as Offer|null;setOffer(next)
  if(next){const{data:t}=await supabase.rpc('oc_provider_offer_customer_trust',{p_booking_id:next.booking_id});setTrust((t?.[0]||null) as Trust|null)}else setTrust(null)
  const{data:review}=await supabase.rpc('oc_provider_pending_customer_review');setPending((review?.[0]||null) as Pending|null)
 }
 useEffect(()=>{let disposed=false;const run=()=>{if(!disposed)load().catch(()=>{})};run();const t=window.setInterval(run,10000);const focus=()=>run();window.addEventListener('focus',focus);return()=>{disposed=true;window.clearInterval(t);window.removeEventListener('focus',focus)}},[])
 const toggle=(tag:string)=>setTags(prev=>prev.includes(tag)?prev.filter(x=>x!==tag):prev.length>=8?prev:[...prev,tag])
 const submit=async()=>{if(!pending||busy)return;setBusy(true);setNotice('');const{error}=await supabase.rpc('oc_provider_rate_customer',{p_booking_id:pending.booking_id,p_rating:rating,p_tags:tags,p_note:note.trim()||null});if(error)setNotice(error.message);else{setNotice('Customer reliability rating saved.');setPending(null);setDismissed(false);setTags([]);setNote('');setRating(5);await load().catch(()=>{});setTimeout(()=>setNotice(''),3500)}setBusy(false)}
 return <>
  {offer&&trust&&<div style={{position:'fixed',right:16,top:122,zIndex:1420,padding:'9px 11px',borderRadius:14,background:'rgba(7,20,38,.94)',border:'1px solid rgba(255,255,255,.12)',color:'#fff',boxShadow:'0 12px 34px rgba(0,0,0,.25)',backdropFilter:'blur(12px)'}}><small style={{display:'block',fontSize:8,fontWeight:900,letterSpacing:'.1em',color:'#8ed7ff'}}>CUSTOMER RELIABILITY</small><strong style={{display:'block',fontSize:16,marginTop:2}}>★ {Number(trust.trust_score||5).toFixed(1)}</strong><span style={{display:'block',fontSize:8,color:'rgba(255,255,255,.52)'}}>{trust.rating_count||0} provider rating{Number(trust.rating_count||0)===1?'':'s'}</span></div>}
  {pending&&!dismissed&&<div role="dialog" aria-modal="false" style={{position:'fixed',left:'50%',transform:'translateX(-50%)',bottom:18,zIndex:2050,width:'min(560px,calc(100vw - 28px))',padding:18,borderRadius:22,background:'#0b1727',color:'#fff',boxShadow:'0 26px 80px rgba(0,0,0,.42)',border:'1px solid rgba(255,255,255,.11)'}}><div style={{display:'flex',justifyContent:'space-between',gap:14}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',color:'#79d1ff'}}>CUSTOMER RELIABILITY</small><h3 style={{fontSize:20,margin:'5px 0 4px'}}>How was {pending.customer_first_name||'the customer'}?</h3><p style={{fontSize:10.5,color:'rgba(255,255,255,.6)',margin:0}}>{pending.service_name} · submitted once and locked to this completed job.</p></div><button type="button" onClick={()=>setDismissed(true)} style={{width:32,height:32,border:0,borderRadius:11,background:'rgba(255,255,255,.08)',color:'#fff',fontSize:18}}>×</button></div><div style={{display:'flex',gap:6,marginTop:14}}>{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>setRating(n)} style={{flex:1,border:0,borderRadius:12,padding:'10px 0',background:n<=rating?'#1765e8':'rgba(255,255,255,.07)',color:'#fff',fontSize:18}}>★</button>)}</div><div style={{display:'flex',flexWrap:'wrap',gap:6,marginTop:11}}>{TAGS.map(tag=><button key={tag} type="button" onClick={()=>toggle(tag)} style={{border:`1px solid ${tags.includes(tag)?'#5bbcff':'rgba(255,255,255,.12)'}`,borderRadius:999,padding:'7px 9px',background:tags.includes(tag)?'rgba(91,188,255,.14)':'transparent',color:'#fff',fontSize:9,fontWeight:800}}>{label(tag)}</button>)}</div><textarea value={note} onChange={e=>setNote(e.target.value.slice(0,1000))} placeholder="Optional private service note" style={{width:'100%',boxSizing:'border-box',minHeight:58,marginTop:10,border:'1px solid rgba(255,255,255,.12)',borderRadius:12,padding:10,background:'rgba(255,255,255,.06)',color:'#fff',font:'inherit',fontSize:10,resize:'vertical'}}/>{notice&&<div style={{fontSize:9,color:'#ffc4c8',marginTop:7}}>{notice}</div>}<button type="button" onClick={submit} disabled={busy} style={{width:'100%',border:0,borderRadius:13,padding:12,marginTop:10,background:'#1765e8',color:'#fff',fontSize:10,fontWeight:900}}>{busy?'SAVING…':'SUBMIT CUSTOMER RATING'}</button></div>}
  {notice&&!pending&&<div role="status" style={{position:'fixed',right:16,bottom:92,zIndex:2100,padding:'10px 12px',borderRadius:12,background:'#111827',color:'#fff',fontSize:10}}>{notice}</div>}
 </>
}
