import { useEffect,useMemo,useState } from 'react'
import { supabase } from './supabase'

type Check={application_id:string;application_number:string;provider_id?:string|null;first_name:string;last_name:string;email:string;check_type:string;required:boolean;status:string;evidence_urls?:string[];notes?:string|null;reviewed_at?:string|null;profile_value?:boolean|null}
const label=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const finalStatus=new Set(['passed','failed','waived','expired'])

export default function ProviderVerificationOpsHost(){
 const[rows,setRows]=useState<Check[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[notes,setNotes]=useState<Record<string,string>>({})
 const load=async()=>{const{data,error}=await supabase.rpc('oc_ops_provider_verifications');if(error)throw error;setRows((data||[]) as Check[])}
 useEffect(()=>{let active=true;const refresh=()=>load().catch(()=>{});supabase.auth.getSession().then(({data})=>{if(active&&data.session)refresh()});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(active&&s)refresh()});return()=>{active=false;data.subscription.unsubscribe()}},[])
 const groups=useMemo(()=>{const map=new Map<string,Check[]>();for(const row of rows){const list=map.get(row.application_id)||[];list.push(row);map.set(row.application_id,list)}return[...map.entries()]},[rows])
 const pending=rows.filter(r=>r.required&&!['passed','waived'].includes(r.status)).length
 const review=async(row:Check,status:string)=>{const key=`${row.application_id}:${row.check_type}`;setBusy(key);setError('');setNotice('');try{const{error}=await supabase.rpc('oc_ops_review_provider_verification',{p_application_id:row.application_id,p_check_type:row.check_type,p_status:status,p_notes:notes[key]||null});if(error)throw error;setNotice(`${label(row.check_type)} → ${label(status)}`);await load()}catch(e:any){setError(e.message||'Verification update failed')}finally{setBusy('')}}
 if(!rows.length&&!open)return null
 return <><button className="ocov-launch" onClick={()=>setOpen(true)}>VERIFICATION QUEUE <b>{pending}</b></button>{open&&<div className="ocov-backdrop" onMouseDown={()=>setOpen(false)}><section className="ocov-sheet" onMouseDown={e=>e.stopPropagation()}><header><div><span>PROVIDER VERIFICATION</span><h2>Checks before dispatch.</h2><p>Application approval opens Provider Command. These checks control whether a provider can actually go online and receive each service.</p></div><button onClick={()=>setOpen(false)}>×</button></header>{error&&<div className="ocov-error">{error}</div>}{notice&&<div className="ocov-notice">{notice}</div>}{groups.length===0?<div className="ocov-empty">No provider verification checks yet.</div>:groups.map(([id,checks])=>{const first=checks[0];return <article className="ocov-provider" key={id}><div className="ocov-provider-head"><div><small>{first.application_number}</small><strong>{first.first_name} {first.last_name}</strong><span>{first.email}</span></div><b>{checks.filter(c=>c.required&&c.status==='passed').length}/{checks.filter(c=>c.required).length} required passed</b></div><div className="ocov-checks">{checks.map(row=>{const key=`${row.application_id}:${row.check_type}`;const canWaive=['license','insurance','vehicle'].includes(row.check_type);return <div className={`ocov-check ${row.status}`} key={key}><div><small>{row.required?'REQUIRED':'CONDITIONAL'}</small><strong>{label(row.check_type)}</strong><span>{label(row.status)}{row.profile_value===true?' · profile synced':''}</span></div><input value={notes[key]||''} onChange={e=>setNotes(n=>({...n,[key]:e.target.value}))} placeholder="Evidence / review note"/><div className="ocov-actions"><button disabled={busy===key} onClick={()=>review(row,'under_review')}>Review</button><button className="pass" disabled={busy===key||row.status==='passed'} onClick={()=>review(row,'passed')}>Pass</button>{canWaive&&<button disabled={busy===key||row.status==='waived'} onClick={()=>review(row,'waived')}>Waive</button>}<button className="fail" disabled={busy===key||row.status==='failed'} onClick={()=>review(row,'failed')}>Fail</button></div></div>})}</div></article>})}<p className="ocov-truth">Core identity, background, skills, and service-area checks cannot be waived. License and insurance requirements are enforced per service.</p></section></div>}</>
}
