import { useEffect,useMemo,useState } from 'react'
import { supabase,startProviderOnboarding } from './supabase'

type Check={check_type:string;required:boolean;status:string;notes?:string|null}
type Status={state:string;application_number?:string;application_status?:string;core_dispatch_ready?:boolean;services?:number;dispatch_ready_services?:number;license_required?:boolean;insurance_required?:boolean;stripe_onboarding_complete?:boolean;stripe_payouts_enabled?:boolean;checks?:Check[]}
const pretty=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function ProviderVerificationReadinessHost(){
 const[status,setStatus]=useState<Status|null>(null),[open,setOpen]=useState(false),[error,setError]=useState('')
 const load=async()=>{const{data,error}=await supabase.rpc('oc_provider_verification_status');if(error)throw error;setStatus(data as Status)}
 useEffect(()=>{let alive=true;const refresh=()=>load().catch(()=>{});supabase.auth.getSession().then(({data})=>{if(alive&&data.session)refresh()});const timer=window.setInterval(refresh,12000);const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive&&s)refresh()});return()=>{alive=false;clearInterval(timer);data.subscription.unsubscribe()}},[])
 const ready=Boolean(status?.core_dispatch_ready)&&Number(status?.dispatch_ready_services||0)>0
 useEffect(()=>{if(status?.state!=='provider')return;document.documentElement.dataset.ocVerificationUi='1';document.documentElement.dataset.ocDispatchReady=ready?'true':'false';const block=(event:Event)=>{const target=event.target as HTMLElement|null;const button=target?.closest?.('.ocp-online');if(!ready&&button&&!button.classList.contains('active')){event.preventDefault();event.stopImmediatePropagation();setOpen(true)}};document.addEventListener('click',block,true);return()=>{document.removeEventListener('click',block,true);delete document.documentElement.dataset.ocVerificationUi;delete document.documentElement.dataset.ocDispatchReady}},[ready,status?.state])
 const checks=useMemo(()=>status?.checks||[],[status]);
 const visible=checks.filter(c=>c.required||['license','insurance'].includes(c.check_type));
 const done=visible.filter(c=>c.status==='passed'||(['license','insurance','vehicle'].includes(c.check_type)&&c.status==='waived')).length
 if(status?.state!=='provider'||ready)return null
 const payoutReady=Boolean(status.stripe_onboarding_complete&&status.stripe_payouts_enabled)
 return <><button className="ocvr-launch" onClick={()=>setOpen(true)}><span>SETUP REQUIRED</span><b>{done + (payoutReady?1:0)}/{visible.length+1}</b><small>{status.dispatch_ready_services||0} services ready</small></button>{open&&<div className="ocvr-backdrop" onMouseDown={()=>setOpen(false)}><section className="ocvr-sheet" onMouseDown={e=>e.stopPropagation()}><header><div><span>PROVIDER LAUNCH READINESS</span><h2>Finish verification before dispatch.</h2><p>Application approval opens Provider Command. ON CALL does not send customer work until the required checks and payout setup are complete.</p></div><button onClick={()=>setOpen(false)}>×</button></header>{error&&<div className="ocvr-error">{error}</div>}<div className="ocvr-summary"><div><small>APPLICATION</small><strong>{status.application_number||'Approved provider'}</strong><span>{pretty(status.application_status||'approved')}</span></div><div><small>APPROVED SERVICES</small><strong>{status.services||0}</strong><span>{status.dispatch_ready_services||0} dispatch-ready</span></div></div><div className="ocvr-checks">{visible.map(check=>{const ok=check.status==='passed'||(['license','insurance','vehicle'].includes(check.check_type)&&check.status==='waived');return <div key={check.check_type} className={ok?'done':''}><i>{ok?'✓':'!'}</i><span><strong>{pretty(check.check_type)}</strong><small>{check.required?'Required':'Conditional'} · {pretty(check.status)}</small></span></div>})}<div className={payoutReady?'done':''}><i>{payoutReady?'✓':'!'}</i><span><strong>Payout account</strong><small>{payoutReady?'Stripe payouts ready':'Stripe onboarding required'}</small></span></div></div>{!payoutReady&&<button className="ocvr-primary" onClick={async()=>{setError('');try{await startProviderOnboarding()}catch(e){setError(e instanceof Error?e.message:'Payout setup could not start.')}}}>Finish payout setup →</button>}<p className="ocvr-truth">Identity, background, skills, and service-area checks must pass. License and insurance are enforced only for services that require them and may be waived only when legitimately not applicable.</p></section></div>}</>
}
