import { useEffect,useState } from 'react'
import { supabase } from './supabase'

type Booking={id:string;service_name:string;status:string}
type Share={url:string;token:string;expires_at:string}

export default function ShareTrackingHost(){
 const[booking,setBooking]=useState<Booking|null>(null),[share,setShare]=useState<Share|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const load=async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session?.user){setBooking(null);return}const{data:u}=await supabase.from('oc_users').select('id,role').eq('auth_id',session.user.id).maybeSingle();if(!u||u.role==='provider'){setBooking(null);return}const{data}=await supabase.from('oc_bookings').select('id,service_name,status').eq('customer_id',u.id).in('status',['matching','assigned','en_route','on_site','working']).order('created_at',{ascending:false}).limit(1);setBooking((data?.[0]||null) as Booking|null)}
 useEffect(()=>{let disposed=false;const run=()=>{if(!disposed)load().catch(()=>{})};run();const t=window.setInterval(run,12000);const focus=()=>run();window.addEventListener('focus',focus);return()=>{disposed=true;window.clearInterval(t);window.removeEventListener('focus',focus)}},[])
 const create=async()=>{if(!booking||busy)return;setBusy(true);setNotice('');const{data,error}=await supabase.rpc('oc_create_booking_share',{p_booking_id:booking.id});if(error)setNotice(error.message);else setShare(data as Share);setBusy(false)}
 const revoke=async()=>{if(!booking||busy)return;setBusy(true);setNotice('');const{error}=await supabase.rpc('oc_revoke_booking_shares',{p_booking_id:booking.id});if(error)setNotice(error.message);else{setShare(null);setNotice('All trusted tracking links for this booking were revoked.');setTimeout(()=>setNotice(''),3500)}setBusy(false)}
 const shareLink=async()=>{if(!share)return;try{if(navigator.share)await navigator.share({title:`ON CALL · ${booking?.service_name||'Live service'}`,text:'Follow this ON CALL service with my temporary trusted tracking link.',url:share.url});else{await navigator.clipboard.writeText(share.url);setNotice('Tracking link copied.')}}catch{}}
 const copy=async()=>{if(!share)return;try{await navigator.clipboard.writeText(share.url);setNotice('Tracking link copied.');setTimeout(()=>setNotice(''),2400)}catch{setNotice('Copy is unavailable on this browser.')}}
 if(!booking)return null
 return <>
  <button type="button" onClick={()=>setOpen(true)} style={{position:'fixed',left:16,bottom:92,zIndex:1460,border:'1px solid rgba(255,255,255,.13)',borderRadius:999,padding:'10px 13px',background:'rgba(7,20,38,.95)',color:'#fff',fontSize:9,fontWeight:900,letterSpacing:'.06em',boxShadow:'0 12px 36px rgba(0,0,0,.28)',backdropFilter:'blur(12px)'}}>SHARE LIVE TRACKING</button>
  {open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:2360,background:'rgba(3,8,15,.58)',display:'grid',placeItems:'end center',padding:12,backdropFilter:'blur(7px)'}}><section style={{width:'min(560px,100%)',borderRadius:23,background:'#f7f9fc',boxShadow:'0 28px 90px rgba(0,0,0,.4)',overflow:'hidden'}}><header style={{padding:'16px 17px',background:'#071426',color:'#fff',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><small style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',color:'#79d1ff'}}>TRUSTED TRACKING</small><h3 style={{fontSize:20,margin:'4px 0 0'}}>{booking.service_name}</h3></div><button type="button" onClick={()=>setOpen(false)} style={{width:34,height:34,border:0,borderRadius:11,background:'rgba(255,255,255,.09)',color:'#fff',fontSize:20}}>×</button></header><div style={{padding:17}}><p style={{fontSize:11,lineHeight:1.55,color:'#637187',margin:'0 0 13px'}}>Share a temporary live tracking link with someone you trust. They can see service status, assigned provider and live location, but never your account, phone, email or payment details.</p>{share?<><div style={{padding:12,borderRadius:14,background:'#eaf2ff',border:'1px solid #cfe0ff',wordBreak:'break-all',fontSize:9.5,color:'#2b4d7a'}}>{share.url}</div><div style={{fontSize:8.5,color:'#8b97a8',marginTop:6}}>Expires {new Date(share.expires_at).toLocaleString()}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:13}}><button type="button" onClick={shareLink} style={{border:0,borderRadius:13,padding:12,background:'#1765e8',color:'#fff',fontSize:10,fontWeight:900}}>SHARE</button><button type="button" onClick={copy} style={{border:'1px solid #d7dee8',borderRadius:13,padding:12,background:'#fff',color:'#334155',fontSize:10,fontWeight:900}}>COPY LINK</button></div><button type="button" onClick={revoke} disabled={busy} style={{width:'100%',border:0,background:'transparent',color:'#b42318',fontSize:9,fontWeight:900,marginTop:13}}>{busy?'REVOKING…':'REVOKE ALL TRACKING LINKS'}</button></>:<button type="button" onClick={create} disabled={busy} style={{width:'100%',border:0,borderRadius:13,padding:13,background:'#1765e8',color:'#fff',fontSize:10,fontWeight:900}}>{busy?'CREATING…':'CREATE TRUSTED TRACKING LINK'}</button>}{notice&&<div style={{fontSize:9.5,color:'#475569',marginTop:10}}>{notice}</div>}</div></section></div>}
 </>
}
