import {useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'

type Ticket={id:string;ticket_number:string;user_id:string;booking_id:string|null;category:string;priority:string;subject:string;description:string;status:string;operator_note:string|null;created_at:string;updated_at:string;resolved_at:string|null;user_email:string|null;user_name:string|null}
const statuses=['all','open','reviewing','waiting_customer','resolved','closed'] as const

export default function SupportOpsHost(){
 const[operator,setOperator]=useState(false);const[tickets,setTickets]=useState<Ticket[]>([]);const[filter,setFilter]=useState<(typeof statuses)[number]>('open');const[open,setOpen]=useState(false);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notes,setNotes]=useState<Record<string,string>>({})
 const load=async()=>{const{data,error}=await supabase.rpc('oc_ops_support_tickets',{p_status:null});if(error)throw error;setTickets((data||[]) as Ticket[])}
 useEffect(()=>{let alive=true;(async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session)return;const{data}=await supabase.rpc('marketplace_operator_check');if(!alive||!data)return;setOperator(true);try{await load()}catch(e){if(alive)setError(e instanceof Error?e.message:'Support queue unavailable')}})();return()=>{alive=false}},[])
 const visible=useMemo(()=>filter==='all'?tickets:tickets.filter(t=>t.status===filter),[tickets,filter])
 const activeCount=tickets.filter(t=>['open','reviewing','waiting_customer'].includes(t.status)).length
 if(!operator)return null
 const update=async(ticket:Ticket,status:string)=>{setBusy(ticket.id+status);setError('');try{const{error}=await supabase.rpc('oc_ops_update_support_ticket',{p_ticket_id:ticket.id,p_status:status,p_note:(notes[ticket.id]??ticket.operator_note??'').trim()||null});if(error)throw error;await load()}catch(e){setError(e instanceof Error?e.message:'Support case update failed')}finally{setBusy('')}}
 return <><button className="ocsops-launch" onClick={()=>setOpen(true)}>SUPPORT <b>{activeCount}</b></button>{open&&<div className="ocsops-backdrop"><section className="ocsops-panel"><header><div><span>ON CALL OPERATIONS</span><h2>Support queue</h2><p>General account, booking, payment, provider, privacy, safety and technical cases.</p></div><button onClick={()=>setOpen(false)}>×</button></header><nav>{statuses.map(status=><button key={status} className={filter===status?'active':''} onClick={()=>setFilter(status)}>{status.replace('_',' ')}{status!=='all'&&<small>{tickets.filter(t=>t.status===status).length}</small>}</button>)}</nav>{error&&<div className="ocsops-error">{error}</div>}<div className="ocsops-list">{visible.length===0?<div className="ocsops-empty">No {filter==='all'?'support':filter.replace('_',' ')} cases.</div>:visible.map(ticket=><article key={ticket.id}><div className="ocsops-ticket-top"><div><span>{ticket.ticket_number}</span><h3>{ticket.subject}</h3></div><div><em className={`priority-${ticket.priority}`}>{ticket.priority}</em><em>{ticket.status.replaceAll('_',' ')}</em></div></div><div className="ocsops-meta"><span>{ticket.user_name||'ON CALL user'}</span>{ticket.user_email&&<a href={`mailto:${ticket.user_email}`}>{ticket.user_email}</a>}<span>{ticket.category}</span>{ticket.booking_id&&<span>Booking {ticket.booking_id.slice(0,8)}…</span>}<span>{new Date(ticket.created_at).toLocaleString()}</span></div><p>{ticket.description}</p><label>Operator note<textarea value={notes[ticket.id]??ticket.operator_note??''} onChange={e=>setNotes(n=>({...n,[ticket.id]:e.target.value}))} placeholder="Add the update the customer should see."/></label><div className="ocsops-actions"><button disabled={!!busy} onClick={()=>void update(ticket,'reviewing')}>Reviewing</button><button disabled={!!busy} onClick={()=>void update(ticket,'waiting_customer')}>Need customer</button><button disabled={!!busy} className="resolve" onClick={()=>void update(ticket,'resolved')}>Resolve</button><button disabled={!!busy} className="close" onClick={()=>void update(ticket,'closed')}>Close</button></div></article>)}</div></section></div>}</>
}
